<?php
/**
 * implementation of hook_ispecies
 */
function gbifmap_ispecies(){
  return array (
    'gbifmap' => array (
      'title' => t ( 'Global Biodiversity Information Facility' ), 
      'description' => t ( 'Some info about GBIF' ),
      'single' => TRUE,
      'callback' => 'gbifmap_ajax_callback' ) );
}

function gbifmap_ajax_callback($term_name, $limit = 20, $urls = array()){
  $items = array ();   
  $request = 'http://fencedine.myspecies.info/?url=' . urlencode ( 'http://data.gbif.org/species/taxonName/ajax/returnType/concept/view/ajaxMapUrls/provider/1/?query=' . $term_name );
  $xml_response = file_get_contents ( $request );  
  if ($xml_response) {    
    $response = new SimpleXMLElement ( $xml_response );    
    $item = array(
      'body' => '<p style="text-align:center"><img id="gbif-map" width="360" height="180" src="http://data.gbif.org/'.$response->taxon->url.'" alt="'.$term_name.'" /></p>',
      'page_url' => 'http://data.gbif.org/species/' . $response->taxon->key
    );    
    $items[] = $item;
    $urls = array($item['page_url']);
  }
  $urls = array('name' => 'GBIF', 'url' => 'http://www.gbif.org/', 'urls'=> $urls);
  $items['urls'] = $urls;
  $items['citation'] = theme('citation_url', $urls);
  return $items;
}

function gbifmap_init(){
  // Add the style sheet to improve the way the map looks.  Note, this will be
  // added to ALL pages, even those not displaying the map (like I give a shit)
  drupal_add_css(drupal_get_path('module','gbifmap').'/gbifmap.css');
}