<?php

// Will login a user from a URL.
function urllogin_menu(){
  return array(
    'urllogin' => array(  
      'title' => 'URL Login',
      'page callback' => 'urllogin_login',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK      
    )
  );
}

function urllogin_login($md5){
  global $user;
  $account = db_fetch_object(db_query("SELECT * FROM {users} WHERE MD5(CONCAT(uid, name, mail)) = '%s' AND uid != 1", $md5));
  $user = $account;
  drupal_goto();
}

function urllogin_mail_alter($message){
  $message['body'][0] = str_replace("!loginurl", url('urllogin/'.md5($message['params']['account']->uid.$message['params']['account']->name.$message['params']['account']->mail), array('absolute' => TRUE)), $message['body'][0]);
}