<?php

/**
 * S.D.Rycroft
 * 
 * Hostmaster_tweaks module
 */
/**
 * Tweak the form is being viewed on the multiple page.
 * 
 * Implementation of hook_form_FORM_ID_alter().
 */
function hostmaster_tweak_form_site_node_form_alter(&$form, &$form_state){
  // Add a JS file which does all the work!
  drupal_add_js(drupal_get_path('module', 'hostmaster_tweak') . '/hostmaster_tweak.js');
}

/**
 * Implementation of hook_perm
 */
function hostmaster_tweak_perm(){
  return array(
    'apply for scratchpad'
  );
}

/**
 * Implementation of hook_menu().asdfasdf
 */
function hostmaster_tweak_menu(){
  return array(
    'apply' => array(
      'title' => 'Apply',
      'description' => 'Apply for a Scratchpad.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'scratchpad_application_form'
      ),
      'access arguments' => array(
        'apply for scratchpad'
      ),
      'file' => 'scratchpad_form.inc',
      'type' => MENU_CALLBACK
    ),
    'apply/results/%' => array(
      'title' => 'Results',
      'page callback' => 'scratchapd_application_results',
      'page arguments' => array(
        2
      ),
      'access arguments' => array(
        'apply for scratchpad'
      ),
      'file' => 'scratchpad_form.inc',
      'type' => MENU_CALLBACK
    ),
    'apply/success' => array(
      'title' => 'Thank you for your application',
      'description' => 'Thank you for your application',
      'page callback' => 'scratchapd_application_success',
      'access arguments' => array(
        'apply for scratchpad'
      ),
      'file' => 'scratchpad_form.inc',
      'type' => MENU_CALLBACK
    )
  );
}

/**
 * Implementation of drush_hook_pre_hosting_task()
 */
function drush_scratchpad_tweak_pre_hosting_task(){
  $task =& drush_get_context('HOSTING_TASK');
  if($task->ref->type == 'site' && ($task->task_type == 'install' || $task->task_type == 'verify')){
    $task->options['scratchpad_apply_form'] = unserialize(db_result(db_query("SELECT data FROM {hostmaster_tweak} WHERE domain LIKE '%s'", $task->ref->title)));
  }
}

/**
 * Implementation of hook_theme().
 */
function hostmaster_tweak_theme(){
  return array(
    'scratchpad_application_form' => array(
      'arguments' => array(
        'form' => NULL,
        'vocabulary' => NULL
      ),
      'file' => 'scratchpad_form.inc'
    )
  );
}