<?php
// $Id$

/**
 * Retrieve the settings array.
 */
function image_convertto_options() {
  $defaults = array(
    'fileformat' => 0
  );
  return variable_get('image_convertto_options', $defaults);
}

/**
 * Implementation of hook_form_alter().
 *
 * Add options to the Image toolkit settings form.
 */
function image_convertto_form_alter($form_id, &$form) {
  if ($form_id == 'system_image_toolkit_settings' && 'imagemagick' == image_get_toolkit()) {
    $options = image_convertto_options();
    $form['image_convertto_options'] = array(
      '#type' => 'fieldset',
      '#title' => t('ImageMagick Convert All Files To'),
      '#collapsible' => FALSE,
      '#description' => t("This setting allows you to force ImageMagick to convert all images to a specified file format."),
      '#tree' => TRUE
    );
    $select_options = array(t('Don\'t Convert'),'jpeg'=>'JPEG','gif'=>'GIF','png'=>'PNG','bmp'=>'BMP');
    $form['image_convertto_options']['fileformat'] = array(
      '#type' => 'select',
      '#title' => t('File format that ALL images should be converted to'),
      '#default_value' => $options['fileformat'],
      '#options' => $select_options,
      '#description' => t('This will force ImageMagick to output all images as the specified format on Resize, Crop or Rotate')
    );
    // Move the buttons below our additions (present in the im_advanced module, so just in case!
    $form['buttons']['#weight'] = 10;    
  } 
}

/**
 * Implementation of hook_imagemagick_alter().
 */
function image_convertto_imagemagick_alter($op, $filepath, &$args) {
  $options = image_convertto_options();
  if($options['fileformat']){
    $args['convertto'] = $options['fileformat'];
  }
}

