<?php
// $Id: nodeform.module,v 1.5 2008/03/07 19:09:53 ximo Exp $

/**
 * Implementation of hook_form_alter().
 */
function nodeform_form_alter(&$form, $form_state, $form_id) {
  // Let users select between node form layouts on the Post settings page.
  if ($form_id == 'node_configure') {
    $form['nodeform_layout'] = array(
      '#type' => 'radios',
      '#title' => t('Layout of node form'),
      '#default_value' => variable_get('nodeform_layout', 'default'),
      '#options' => array(
        'default' => t('Default'),
        'accordion' => t('Accordion'),
        'vertical' => t('Vertical tabs'),
      ),
      '#description' => t('Select which layout to use on the node form.'),
    );

    $form['#submit'][] = 'nodeform_settings_form_submit';
    $form['buttons']['#weight'] = 10;
  }

  // Add JS and CSS files of the selected layout to the node form.
  elseif ($form['#id'] == 'node-form') {
    $module_path = drupal_get_path('module', 'nodeform');

    $form['buttons']['#prefix'] .= '<div id="nodeform-buttons">';
    $form['buttons']['#suffix'] .= '</div>';

    switch (variable_get('nodeform_layout', 'default')) {
      // Accordion:
      case 'accordion':
        drupal_add_js($module_path .'/accordion/jquery.accordion.js', 'module');
        drupal_add_js($module_path .'/accordion/accordion.js', 'module');
        drupal_add_css($module_path .'/accordion/accordion.css', 'module');
        break;
      // Vertical tabs:
      case 'vertical':
        drupal_add_js($module_path .'/vertical_tabs/ui.tabs.min.js', 'module');
        drupal_add_js($module_path .'/vertical_tabs/vertical_tabs.js', 'module');
        drupal_add_css($module_path .'/vertical_tabs/vertical_tabs.css', 'module');
        break;
    }
  }
}

/**
 * Custom submit handler for admin/content/node-settings.
 */
function nodeform_settings_form_submit($form, &$form_state) {
  if ($form['#post']['op'] == t('Reset to defaults')) {
    variable_set('nodeform_layout', 'default');
  }
  else {
    variable_set('nodeform_layout', $form_state['values']['nodeform_layout']);
  }
}
