<?php

/**
 * An attempt at creating a module for inputting specimens into Drupal
 * 
 * This module uses the Darwincore Schema (DwC 1.21
 */

/**
 * Implementation of hook_viewsapi
 */
function darwincore_views_api(){
  return array(
    'api' => 2,
    'path' => drupal_get_path('module','darwincore') . "/views"
  );
}

/**
 * Following two hooks are related to the node_import module.
 */
function darwincore_node_import_fields($type){
  if($type == 'node:darwincore' || $type == 'node:darwincorelocation'){      
    $vocabularies = taxonomy_get_vocabularies();
    foreach($vocabularies as $vocabulary){
      if($vocabulary->module == 'darwincore'){
        $options[$vocabulary->name] = taxonomy_get_tree($vocabulary->vid);
      }
    }
  }
  if($type == 'node:darwincore'){
    $fields = array();
    $allowed_values = array();
    foreach($options['Basis of record'] as $option){
      $allowed_values[$option->tid] = $option->name;
    }
    $fields['basisofrecord'] = array(
      'title' => t('Basis of record'),
      'group' => t('Darwincore fields'),
      'allowed_values' => $allowed_values
    );
    $allowed_values = array();
    foreach($options['Sex'] as $option){
      $allowed_values[$option->tid] = $option->name;
    }
    $fields['sex'] = array(
      'title' => t('Sex'),
      'group' => t('Darwincore fields'),
      'allowed_values' => $allowed_values
    );
    $fields['institutioncode'] = array(
      'title' => t('Institution code'),
      'group' => t('Darwincore fields')      
    );
    $fields['collectioncode'] = array(
      'title' => t('Collection code'),
      'group' => t('Darwincore fields')      
    );
    $fields['cataloguenumbertext'] = array(
      'title' => t('Catalogue number text'),
      'group' => t('Darwincore fields')      
    );
    $fields['taxonomicname'] = array(
      'title' => t('Taxonomic name'),
      'group' => t('Darwincore fields')
    );
    $fields['identificationqualifier'] = array(
      'title' => t('Identification qualifier/modifier'),
      'group' => t('Darwincore fields')
    );
    $fields['identifiedby'] = array(
      'title' => t('Identified by'),
      'group' => t('Darwincore fields')
    );
    $fields['dateidentified'] = array(
      'title' => t('Date identified'),
      'group' => t('Darwincore fields')
    );  
    $allowed_values = array();
    foreach($options['Type status'] as $option){
      $allowed_values[$option->tid] = $option->name;
    }
    $fields['typestatus'] = array(
      'title' => t('Type status'),
      'group' => t('Darwincore fields'),
      'allowed_values' => $allowed_values
    );
    $fields['collectornumber'] = array(
      'title' => t('Collector number'),
      'group' => t('Darwincore fields')
    );
    $fields['fieldnumber'] = array(
      'title' => t('Field number'),
      'group' => t('Darwincore fields')
    );
    $fields['collector'] = array(
      'title' => t('Collector'),
      'group' => t('Darwincore fields')
    );
    $fields['earliestdatecollected'] = array(
      'title' => t('Earliest date collected'),
      'group' => t('Darwincore fields')
    );
    $fields['lateestdatecollected'] = array(
      'title' => t('Latest date collected'),
      'group' => t('Darwincore fields')
    );
    $fields['fieldnotes'] = array(
      'title' => t('Field notes'),
      'group' => t('Darwincore fields')
    );
    $fields['lifestage'] = array(
      'title' => t('Life stage'),
      'group' => t('Darwincore fields')
    );
    $fields['count'] = array(
      'title' => t('Individual count'),
      'group' => t('Darwincore fields')
    );
    $fields['genbanknum'] = array(
      'title' => t('Genbank number'),
      'group' => t('Darwincore fields')
    );
    $fields['othercataloguenum'] = array(
      'title' => t('Other catalogue numbers'),
      'group' => t('Darwincore fields')
    );
    $fields['remarks'] = array(
      'title' => t('Remarks'),
      'group' => t('Darwincore fields')
    );
    $fields['locationnode'] = array(
      'title' => t('Location node'),
      'group' => t('Darwincore fields')
    );
    return $fields;
  } else if($type == 'node:darwincorelocation'){
    $fields['locality'] = array(
      'title' => t('Locality'),
      'group' => t('Location')
    );
    $fields['stateprovince'] = array(
      'title' => t('State province'),
      'group' => t('Location')
    );
    $allowed_values = array();
    foreach($options['Continent/BodyOfWater'] as $option){
      $allowed_values[$option->tid] = $option->name;
    }
    $fields['continentocean'] = array(
      'title' => t('Continent/BodyOfWater'),
      'group' => t('Location'),
      'allowed_values' => $allowed_values
    );
    $fields['islandgroup'] = array(
      'title' => t('Island group'),
      'group' => t('Location')
    );
    $fields['island'] = array(
      'title' => t('Island'),
      'group' => t('Location')
    );
    $fields['county'] = array(
      'title' => t('County'),
      'group' => t('Location')
    );
    $fields['geodeticdatum'] = array(
      'title' => t('Geodetic Datum'),
      'group' => t('Location')
    );
    $fields['verbatimcoordinatesystem'] = array(
      'title' => t('Verbatim Coordinate System'),
      'group' => t('Location')
    );
    $fields['georeferenceprotocol'] = array(
      'title' => t('Georeference Protocol'),
      'group' => t('Location')
    );
    $fields['coordinateuncertainty'] = array(
      'title' => t('Coordinate uncertainty in meters'),
      'group' => t('Location')
    );
    $fields['georeferenceremarks'] = array(
      'title' => t('Georeference remarks'),
      'group' => t('Location')
    );
    $fields['minelevation'] = array(
      'title' => t('Minimum elevation in meters'),
      'group' => t('Location')
    );
    $fields['maxelevation'] = array(
      'title' => t('Maximum elevation in meters'),
      'group' => t('Location')
    );
    $fields['mindepth'] = array(
      'title' => t('Minimum depth in meters'),
      'group' => t('Location')
    );
    $fields['maxdepth'] = array(
      'title' => t('Maximum depth in meters'),
      'group' => t('Location')
    );
    return $fields;
  }
}
function darwincore_node_import_fields_alter(&$fields, $type){
  if($type == 'node:darwincore' || $type == 'node:darwincorelocation'){ 
    // Unset all vocabulary fields - we'll do the association ourselves.
    $vocabularies_text = t('Vocabularies');
    foreach($fields as $key => $field){
      if($field['group'] == $vocabularies_text){
        unset($fields[$key]);
      }
    }
    // Hide the body field
    $fields['body']['is_mappable'] = FALSE;
    $fields['format']['is_mappable'] = FALSE;
  }
  if($type == 'node:darwincore'){
    // Sort the title field
    $fields['title']['is_mappable'] = FALSE;
    $fields['title']['default_value'] = 'ANT'; // Auto Node Title
    $fields['title']['allow_empty'] = TRUE;
    $fields['title']['map_required'] = FALSE;
  }
  if($type == 'node:darwincorelocation'){
    // Change the title field
    $fields['title']['group'] = t('Location');
  }
}

/**
 * Implementation of hook_node_info
 */
function darwincore_node_info() {
  return array(
    'darwincore' => array(
      'name' => t('Specimen (DwC 1.2.1)'),
      'module' => 'darwincore',
      'description' => t('A Specimen content type based upon Darwincore 1.2.1')    
    ),
    'darwincorelocation' => array(
      'name' => t('Location (DwC 1.2.1)'),
      'module' => 'darwincorelocation',
      'description' => t('A location which conforms to Darwincore 1.2.1, and can be associated with multiple specimens')
    )
  );
}

// hook_perm
function darwincore_perm(){
  return array(
    'create darwincore content',
    'delete darwincore content',
    'delete own darwincore content',
    'edit darwincore content',
    'edit own darwincore content'
  );
}
/**
 * Implementation of hook_menu()
 */
function darwincore_menu(){
  $items = array();
  $items['darwincore/autocomplete'] = array(
    'title' => 'Autocomplete darwincore thingumy',
    'page callback' => 'darwincore_autocomplete',
    'access arguments' => array('create darwincore content'),
    'file' => 'darwincore.autocomplete.inc',
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * Implementation of hook_form()
 */
function darwincore_form(&$node) {
  // Add the JS required.
  jquery_ui_add('ui.tabs');
  drupal_add_js(drupal_get_path('module','darwincore').'/darwincore.js');
  // Add the CSS
  drupal_add_css(drupal_get_path('module','jquery_ui').'/jquery.ui/themes/smoothness/ui.all.css');
  // Hide the title
  $form['title'] = array(
    '#type' => 'hidden',
    '#value' => $node->title
  );
  
  // Tabs component
  $form['tabs'] = array(
    '#prefix' => '<div id="tabs">    
    <ul>
      <li><a href="#fragment-1"><span>Required</span></a></li>
      <li><a href="#fragment-2"><span>Taxonomy</span></a></li>
      <li><a href="#fragment-3"><span>Collection</span></a></li>
      <li><a href="#fragment-4"><span>Miscellaneous</span></a></li>
      <li><a href="#fragment-5"><span>Location</span></a></li>
    </ul>',
    '#suffix' => '</div>'
  );
//-- Required tab -----------------------------------------
  $form['tabs']['requiredfields'] = array(
    '#prefix' => '<div id="fragment-1">',
    '#suffix' => '</div>'
  );
  $form['tabs']['requiredfields']['basisofrecord'] = _darwincore_get_vocabulary_form('Basis of record',$node->basisofrecord,'A descriptive term indicating whether the record represents an object or observation.');
  $form['tabs']['requiredfields']['basisofrecord']['#required'] = true;
  $form['tabs']['requiredfields']['institutioncode'] = array(
    '#type' => 'textfield',
    '#autocomplete_path' => 'darwincore/autocomplete/institutioncode',
    '#default_value' => $node->institutioncode,
    '#description' => t('The code (or acronym) identifying the institution administering the collection in which the organism record is cataloged. No global registry exists for institutional codes; use the code that is "standard" at your institution or in your discipline.'),
    '#title' => t('Institution code'),
    '#required' => true
  );
  $form['tabs']['requiredfields']['collectioncode'] = array(
  '#type' => 'textfield',
  '#title' => t('Collection code'),
  '#autocomplete_path' => 'darwincore/autocomplete/collectioncode',
  '#default_value' => $node->collectioncode,
  '#description' => t('The code (or acronym) identifying the collection within the institution in which the organism record is cataloged.'),
  '#required' => true
  );
  $form['tabs']['requiredfields']['cataloguenumbertext'] = array(
  '#type' => 'textfield',
  '#default_value' => $node->cataloguenumbertext,
  '#description' => t('The catalogue number (text) for this specimen'),
  '#title' => t('Catalogue number text'),
  '#required' => true
  );
//-- Identification tab -----------------------------------
  $form['tabs']['taxonomy'] = array(
    '#prefix' => '<div id="fragment-2">',
    '#suffix' => '</div>'
  );
  $form['tabs']['taxonomy']['taxonomicname'] = array(
  '#type' => 'textfield',
  '#title' => t('Taxonomic name'),
  '#autocomplete_path' => 'darwincore/autocomplete/taxonomicname',
  '#default_value' => _darwincore_get_taxonomicname($node->taxonomicname),
  '#description' => t('The full name of the lowest level taxon to which the organism has been identified in the most recent accepted determination, specified as precisely as possible')
  );
  $form['tabs']['taxonomy']['identificationqualifier'] = array(
  '#type' => 'textfield',
  '#title' => t('Identification qualifier/modifier'),
  '#autocomplete_path' => 'darwincore/autocomplete/identificationqualifier',
  '#default_value' => $node->identificationqualifier,
  '#description' => t('A standard term to qualify the identification of the organism when doubts have arisen as to its identity. Examples: "cf.", "aff.", "subspecies in question"')
  );
  $form['tabs']['taxonomy']['identifiedby'] = array(
  '#type' => 'textfield',
  '#title' => t('Identified by'),
  '#autocomplete_path' => 'darwincore/autocomplete/identifiedby',
  '#default_value' => $node->identifiedby,
  '#description' => t('The name(s) of the person(s) who applied the ScientificName to the object or observation. Example: James Earl Jones.')
  );
  $form['tabs']['taxonomy']['dateidentified'] = array(
  '#type' => 'date',
  '#title' => t('Date identified'),
  '#required' => true,
  '#default_value' => (empty($node->dateidentified)) ? array('day'=>1,'month'=>1,'year'=>2000) : $node->dateidentified,
  '#description' => t('The date-time in the Common Era calendar in which the object or observation was identified as being a member of the taxon given in the ScientificName.')
  );
  $form['tabs']['taxonomy']['typestatus'] = _darwincore_get_vocabulary_form('Type status', $node->typestatus, t('A list of one or more nomenclatural types represented by the object.'));
  
  //-- Collection tab ---------------------------------------
  $form['tabs']['collection'] = array(
    '#prefix' => '<div id="fragment-3">',
    '#suffix' => '</div>'
  );
  $form['tabs']['collection']['collectornumber'] = array(
  '#type' => 'textfield',
  '#title' => t('Collector number'),
  '#default_value' => $node->collectornumber,
  '#description' => t('An identifying string applied to the object or observation at the time of collection. Serves as a link between field notes and the object or observation.')
  );
  $form['tabs']['collection']['fieldnumber'] = array(
  '#type' => 'textfield',
  '#title' => t('Field number'),
  '#default_value' => $node->fieldnumber,
  '#description' => t('An identifying string applied to a set of material that resulted from a single collecting event.')
  );
  $form['tabs']['collection']['collector'] = array(
  '#type' => 'textfield',
  '#title' => t('Collector'),
  '#default_value' => $node->collector,
  '#description' =>t('The name(s) of the collector(s) of the original data for the cataloged item.'),
  '#autocomplete_path' => 'darwincore/autocomplete/collector'
  );
  $form['tabs']['collection']['daterange'] = array(
  '#type' => 'fieldset',
  '#title' => t('Collection date range'),
  '#collapsible' => false,
  '#collapsed' => false,
  '#description' => t('The earliest and latest date-time (Common Era calendar) in a date-time period during which an organism or group of organisms was collected or observed. If the event is recorded as occurring at a single date-time, populate both EarliestDateCollected and LatestDateCollected with the same value.')
  );
  $form['tabs']['collection']['daterange']['earliestdatecollected'] = array(
  '#type' => 'date',
  '#title' => t('Earliest date collected'),
  '#default_value' => (empty($node->earliestdatecollected)) ? array('year'=>2000,'month'=>1,'day'=>1) : $node->earliestdatecollected
  );
  $form['tabs']['collection']['daterange']['latestdatecollected'] = array(
  '#type' => 'date',
  '#title' => t('Latest date collected'),
  '#default_value' => (empty($node->latestdatecollected)) ? array('year'=>2000,'month'=>1,'day'=>1) : $node->latestdatecollected
  );
  $form['tabs']['collection']['fieldnotes'] = array(
  '#type' => 'textarea',
  '#title' => t('Field notes'),
  '#default_value' => $node->fieldnotes,
  '#rows' => 3,
  '#description' => t('Notes taken in the field for the cataloged item.')
  );
  $form['locate'] = array(
    '#prefix' => '<div id="fragment-5">',
    '#suffix' => '</div>',
    '#title' => t('Location')
  );
  $results = db_query("SELECT nr.title FROM node n, node_revisions nr WHERE n.nid = nr.nid AND n.type = 'darwincorelocation' ORDER BY nr.title;");
  $location_nodes[0]=t('-- None --');
  while($row = db_fetch_array($results)){
    $location_nodes[$row['title']]=$row['title'];
  }
  // $form['locate']['locationnode'] = array(
  //   '#type' => 'select',
  //   '#title' => t('Select a previously created location'),
  //   //'#multiple' => 1,
  //   '#size' => 10,
  //   '#default_value' => array_pop(db_fetch_array(db_query("SELECT r.title FROM {node} n, {node_revisions} r WHERE n.vid = r.vid AND n.nid = %d",$node->locationnode))),
  //   '#options' => $location_nodes
  // );
  $form['locate']['togglebelow'] = array(
    '#value' => '<a href="#" onclick="$(\'#locationfieldset\').show();$(\'#edit-creatingnewlocation\').val(\'1\');$(\'#edit-locationnode\').attr(\'disabled\',\'disabled\');return false;">Or, Create a new location</a>'
  );
  $form['locate']['createlocation'] = array(
    '#suffix' => '</div>',
    '#prefix' => '<div id="locationfieldset" style="display:none">',
    '#type' => 'fieldset',
    '#title' => t('Location'),
    '#collapsed' => 0
  );
  $form['locate']['createlocation']['cancel'] = array(
    '#value' => '<a href="#" onclick="$(\'#locationfieldset\').hide();$(\'#edit-creatingnewlocation\').val(\'0\');$(\'#edit-locationnode\').removeAttr(\'disabled\');return false;">Cancel creating new location</a>',
    '#weight' => -1000
  );
  $form['creatingnewlocation'] = array(
    '#type' => 'hidden',
    '#default_value' => 0,
    '#options' => array(1,0)
  );
  $location_form = darwincorelocation_form($node, $param);
  $location_form['type']['#value'] = 'darwincorelocation';
  location_form_alter($form, $form_state, $form_id);
  $location_form['locationtitle'] = $location_form['title'];
  $location_form['locationtitle']['#required'] = 0;
  if($location_form['locationtitle']['#value']==$form['title']['#value']){
    unset($location_form['locationtitle']['#value']);
  }
  unset($location_form['title']);
  unset($location_form['type']['#value']);
  $location_form['locations'] = $location_form['locations'][0];
  $location_form['locations']['#weight'] = -100;
  $keys = array_keys($location_form);
  foreach($keys as $key){
    $form['locate']['createlocation'][$key] = $location_form[$key];
  }
  $form['tabs']['misc'] = array(
    '#prefix' => '<div id="fragment-4">',
    '#suffix' => '</div>'
  );
  $form['tabs']['misc']['sex'] = _darwincore_get_vocabulary_form('Sex', $node->sex, '');
  $form['tabs']['misc']['lifestage'] = array(
  '#type' => 'textfield',
  '#title' => t('Life stage'),
  '#default_value' => $node->lifestage,
  '#description' => t('The age class or life stage of the biological individual represented by the catalogued object or observation. Examples: "adult", "mature", "juvenile", "eft", "nymph", "seedling", "seed", "egg"'),
  '#autocomplete_path' => 'darwincore/autocomplete/lifestage'
  );
  $form['tabs']['misc']['preparations'] = array(
  '#value' => '<p><b>Preparations</b><br/>We will shortly be adding the facility to record preparations of specimens</p>'
  );
  $form['tabs']['misc']['tissues'] = array(
  '#value' => '<p><b>Tissues</b><br/>We will shortly be adding the facility to record tissues samples derived from specimens</p>'
  );
  $form['tabs']['misc']['count'] = array(
  '#type' => 'textfield',
  '#title' => t('Individual count'),
  '#description' => t('The number of individuals present in the lot or container. Not to be used for observations.'),
  '#default_value' => $node->count
  );
  $form['tabs']['misc']['genbanknum'] = array(
  '#type' => 'textfield',
  '#title' => t('Genbank number'),
  '#default_value' => $node->genbanknum
  );
  $form['tabs']['misc']['othercataloguenum'] = array(
  '#type' => 'textarea',
  '#title' => t('Other catalogue numbers'),
  '#description' => t('A list of previous or alternative fully qualified catalog numbers for the same object or observation, whether in the current collection or in any other.  One per line'),
  '#default_value' => $node->othercataloguenum
  );
  $form['tabs']['misc']['tissues'] = array(
  '#value' => '<p><b>Related specimens</b><br/>We hope to be able to link specimens together shortly.</p>'
  );
  $form['tabs']['misc']['remarks'] = array(
  '#type' => 'textarea',
  '#title' => t('Remarks'),
  '#default_value' => $node->remarks,
  '#description' => t('General comments about the specimen that others may find usefull.')
  );
  $form['#submit'][] = 'darwincore_submit';
  return $form;

}
/**
 * Implementation of hook_form()
 *
 * @param unknown_type $node
 * @param unknown_type $param
 * @return array $form
 */
function darwincorelocation_form(&$node, &$param){
  $form['title'] = array(
    '#title' => t('Location title (Used when referencing this location)'),
    '#required' => 1,
    '#type' => 'textfield',
    '#default_value' => $node->title,
    '#weight' => -200
  );
  $form['locality'] = array(
  '#title' => t('Locality'),
  '#weight' => -150,
  '#description' => t('The description of the locality from which the cataloged item was collected, sans geographic information provided in other geographic fields.'),
  '#default_value' => $node->locality,
  '#type' => 'textarea',
  '#rows' => 3
  );
  $form['extrafields'] = array(
  '#type' => 'fieldset',
  '#title' => t('Extra Fields'),
  '#collapsed' => 1,
  '#collapsible' => 1,
  '#weight' => -50
  );
  $form['extrafields']['stateprovince'] = array(
  '#title' => t('State province'),
  '#description' => t('The full, unabbreviated name of the state, province, or region (i.e., the next smaller political region than Country) from which the cataloged item was collected.'),
  '#type' => 'textfield',
  '#default_value' => $node->stateprovince,
  '#autocomplete_path' => 'darwincore/autocomplete/stateprovince'
  );
  $form['extrafields']['continentocean'] = _darwincore_get_vocabulary_form('Continent/BodyOfWater', $node->continentocean, t('The full, unabbreviated name of the continent or ocean from which the cataloged item was collected.'));
  $form['extrafields']['islandgroup'] = array(
  '#title' => t('Island group'),
  '#type' => 'textfield',
  '#description' => t('The full, unabbreviated name of the island group from which the cataloged item was collected.'),
  '#default_value' => $node->islandgroup,
  '#autocomplete_path' => 'darwincore/autocomplete/islandgroup'
  );
  $form['extrafields']['island'] = array(
  '#title' => t('Island'),
  '#type' => 'textfield',
  '#description' => t('The full, unabbreviated name of the island from which the cataloged item was collected.'),
  '#default_value' => $node->island,
  '#autocomplete_path' => 'darwincore/autocomplete/island'
  );
  $form['extrafields']['county'] = array(
  '#title' => t('County'),
  '#description' => t('The full, unabbreviated name of the county, shire, or municipality (i.e., the next smaller political region than StateProvince) from which the cataloged item was collected.'),
  '#default_value' => $node->county,
  '#type' => 'textfield',
  '#autocomplete_path' => 'darwincore/autocomplete/county'
  );
  $form['extrafields']['geodeticdatum'] = array(
  '#title' => t('Geodetic Datum'),
  '#description' => t('The geodetic datum to which the latitude and longitude refer. If not known, use "not recorded".'),
  '#default_value' => $node->geodeticdatum,
  '#type' => 'textfield',
  '#autocomplete_path' => 'darwincore/autocomplete/geodeticdatum'
  );
  $form['extrafields']['verbatimcoordinatesystem'] = array(
  '#title' => t('Verbatim Coordinate System '),
  '#description' => t('The name of the system in which the verbatim geographic coordinates were recorded. Examples: "decimal degrees", "degrees minutes seconds", "degrees decimal minutes", "UTM"'),
  '#type' => 'textfield',
  '#autocomplete_path' => 'darwincore/autocomplete/verbatimcoordinatesystem',
  '#default_value' => $node->verbatimcoordinatesystem
  );
  $form['extrafields']['georeferenceprotocol'] = array(
  '#title' => t('Georeference Protocol'),
  '#description' => t('A reference to the methods used for determining the coordinates and uncertainties. Example: "http://manisnet.org/GeorefGuide.html".'),
  '#type' => 'textfield',
  '#autocomplete_path' => 'darwincore/autocomplete/georeferenceprotocol',
  '#default_value' => $node->georeferenceprotocol
  );
  $form['extrafields']['coordinateuncertainty'] = array(
  '#title' => t('Coordinate uncertainty in meters'),
  '#description' => t(' 	The upper limit of the distance (in meters) from the given latitude and longitude describing a circle within which the whole of the described locality must lie. Use NULL where the uncertainty is unknown, cannot be estimated, or is not applicable.'),
  '#type' => 'textfield',
  '#default_value' => $node->coordinateuncertainty
  );
  $form['extrafields']['georeferenceremarks'] = array(
  '#title' => t('Georeference remarks'),
  '#description' => t('Comments about the spatial description determination, explaining assumptions made in addition or opposition to the those formalized in the method referred to in GeoreferenceProtocol.'),
  '#type' => 'textarea',
  '#default_value' => $node->georeferenceremarks,
  '#rows' => 3
  );
  $form['extrafields']['elevation'] = array(
    '#title' => t('Elevation'),
    '#type' => 'fieldset',
    '#collapsible' => 0,
    '#collapsed' => 0
  );
  $form['extrafields']['elevation']['minelevation'] = array(
  '#title' => t('Minimum elevation in meters'),
  '#description' =>t('The minimum distance in meters above (positive) or below sea level of the collecting locality.'),
  '#type' => 'textfield',
  '#default_value' => $node->minelevation
  );
  $form['extrafields']['elevation']['maxelevation'] = array(
  '#title' => t('Maximum elevation in meters'),
  '#description' =>t('The maximum distance in meters above (positive) or below sea level of the collecting locality.'),
  '#type' => 'textfield',
  '#default_value' => $node->maxelevation
  );
  $form['extrafields']['depth'] = array(
    '#title' => t('Depth'),
    '#type' => 'fieldset',
    '#collapsible' => 0,
    '#collapsed' => 0
  );
  $form['extrafields']['depth']['mindepth'] = array(
  '#title' => t('Minimum depth in meters'),
  '#description' => t('The minimum or actual depth at which the collection or observation was made. Use positive values for locations below the surface. Examples: 0 (for a depth of up to 10m). 50 (for a depth between 50m and 100m).'),
  '#type' => 'textfield',
  '#default_value' => $node->mindepth
  );
  $form['extrafields']['depth']['maxdepth'] = array(
  '#title' => t('Maximum depth in meters'),
  '#description' => t('The maximum or actual depth at which the collection or observation was made. Use positive values for locations below the surface. Examples: 10 (for a depth of up to 10m). 100 (for a depth between 50m and 100m).'),
  '#type' => 'textfield',
  '#default_value' => $node->maxdepth
  );
  return $form;
}
/**
 * Implementation of hook_access()
 */
function darwincore_access($op, $node, $account){
  if ($op == 'create'){
    return user_access('create darwincore content', $account);
  }
  if ($op =='update'){
    if(user_access('edit own darwincore content', $account) && $account->uid == $node->uid){
      return true;
    }
    else {
      return user_access('edit darwincore content', $account);
    }
  }
  if ($op =='delete'){
    if(user_access('delete own darwincore content', $account) && $account->uid == $node->uid){
      return true;
    }
    else {
      return user_access('delete darwincore content', $account);
    }
  }
  return false;
}
function darwincorelocation_access($op, $node, $account){
  return darwincore_access($op, $node, $account);  
}

/**
 * Implementation of hook_validate()
 */
function darwincore_validate($node, &$form){
  // Check the treasure for valuables.
  
  // Check that a BasisOfRecord has been selected
  if ($node->basisofrecord==0){
    form_set_error('basisofrecord', t('Basis of record field is required.'));
  }
  // Check that a taxonomic name has been chuffin' set, and not a new one
  // typed in.
  // Change the Taxonomicname into an ID (This is done here, rather than being sent in the form
  // to avoid confusing the naughty little taxonomists).
  if (trim($node->taxonomicname)!=''){
    $node->taxonomicname = _darwincore_get_taxonomicname($node->taxonomicname);
    if (!$node->taxonomicname){
      // The term isn't correct, kill them
      form_set_error('taxonomicname',t('You must enter a name that is present in a taxonomy on your site'));
    }
  }
  // If we're creating a new location, ensure that it has a title set
  if($node->creatingnewlocation){
    // Is the title set?
    if(strlen(trim($node->locationtitle))==0){
      form_set_error('locationtitle',t('You must enter a Location Description if adding a new location'));
    }
  }
}
function darwincorelocation_validate($node, &$form){
  // Lets make sure the location title is UNIQUE!
  $count = array_pop(db_fetch_array(db_query("SELECT COUNT(*) FROM {node} n, {node_revisions} r WHERE n.vid = r.vid AND type = 'darwincorelocation' AND TRIM(LOWER(r.title)) = '%s' AND vid != %d", trim(strtolower($node->title)), $node->vid)));
  if($count){
    form_set_error('title', t('The title must be unique'));
  }
  // Lets make sure that elevation and other fields only contain numbers (1,45, or 2.23 etc)
  /*
    $node->minelevation,
    $node->maxelevation,
    $node->mindepth,
    $node->maxdepth,*/
  if(trim(preg_replace("/[0-9\.]*/","",$node->minelevation)) != ''){
    // Looks like this isn't right, set an error
    form_set_error('minelevation', t('Minimum elevation must be a number'));
  }
  if(trim(preg_replace("/[0-9\.]*/","",$node->maxelevation)) != ''){
    // Looks like this isn't right, set an error
    form_set_error('maxelevation', t('Maximum elevation must be a number'));
  }
  if(trim(preg_replace("/[0-9\.]*/","",$node->mindepth)) != ''){
    // Looks like this isn't right, set an error
    form_set_error('mindepth', t('Minimum depth must be a number'));
  }
  if(trim(preg_replace("/[0-9\.]*/","",$node->maxdepth)) != ''){
    // Looks like this isn't right, set an error
    form_set_error('maxdepth', t('Maximum depth must be a number'));
  }
  
  
}
/**
 * Implementation of hook_view().
 */
function darwincore_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);
  $output = theme('darwincore_full_page', $node);
  if($node->locationnode){
    $locationnode = node_load($node->locationnode);
    darwincorelocation_view($locationnode);
    $output .= $locationnode->content['#value'];
  }
  $node->content = array(
    '#value' => $output,
    '#weight' => -10
  );
  return $node;
}
function darwincorelocation_view($node, $teaser = FALSE, $page = FALSE){
  $node = node_prepare($node, $teaser);
  $node->content = array(
    '#value' => theme('darwincorelocation_full_page',$node),
    '#weight' => -10
  );
  return $node;
}

/**
 * Implementation of hook_theme
 */
function darwincore_theme($existing, $type, $theme, $path){
  return array(
    'darwincore_full_page' => array(
      'arguments' => array('node' => NULL),
      'file' => 'darwincore.pages.inc'
    ),
    'darwincorelocation_full_page' => array(
      'arguments' => array('node' => NULL),
      'file' => 'darwincore.pages.inc'
    )
  );
}

/**
 * Implemenatation of hook_insert($node)
 */
function darwincore_insert($node){
  // If we're creating a new location, chuffin' do so.
  if($node->creatingnewlocation){
    // The only required field is set for the location, lets set it, and then set the other field to the nid of this new
    // location
    $location_node = clone $node;
    unset(
      $location_node->nid,
      $location_node->vid,
      $location_node->created,
      $location_node->changed,
      $location_node->basisofrecord,
      $location_node->institutioncode,
      $location_node->collectioncode,
      $location_node->cataloguenumbertext,
      $location_node->taxonomicname,
      $location_node->identificationqualifier,
      $location_node->identifiedby,
      $location_node->dateidentified,
      $location_node->typestatus,
      $location_node->collectornumber,
      $location_node->fieldnumber,
      $location_node->collector,
      $location_node->earliestdatecollected,
      $location_node->latestdatecollected,
      $location_node->fieldnotes,
      $location_node->sex,
      $location_node->lifestage,
      $location_node->count,
      $location_node->genbanknum,
      $location_node->othercataloguenum,
      $location_node->remarks,
      $location_node->locationnode,
      $location_node->creatingnewlocation
    );
    $location_node->type = 'darwincorelocation';
    $location_node->title = $location_node->locationtitle;
    $location_node->locations = array($location_node->locations);
    node_save($location_node);
    $node->locationnode = $location_node->nid;
  }
  // Lets not insert the default date of 2000/1/1
  $dates = array(&$node->dateidentified,&$node->earliestdatecollected,&$node->latestdatecollected);
  foreach($dates as &$date){
    if ($date['year']==2000 && $date['month']==1 && $date['day']==1){
      $date = 'NULL';
    }
    else {
      $date = $date['year']."/".$date['month']."/".$date['day'];
    }
  }
  // Change the taxonomic name to an ID (this should be valid as we've checked it already).
  $node->taxonomicname = _darwincore_get_taxonomicname($node->taxonomicname);
  $result = db_query("INSERT INTO {darwincore} (nid,vid,institutioncode,collectioncode,cataloguenumbertext,identificationqualifier,identifiedby,dateidentified,collectornumber,fieldnumber,collector,earliestdatecollected,latestdatecollected,fieldnotes,count,genbanknum,remarks,lifestage,basisofrecord,sex,taxonomicname,typestatus,othercataloguenum,locationnode) VALUES (%d,%d,'%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s',%d,'%s','%s','%s',%d,%d,%d,%d,'%s',%d);",
    $node->nid,
    $node->vid,
    $node->institutioncode,
    $node->collectioncode,
    $node->cataloguenumbertext,
    $node->identificationqualifier,
    $node->identifiedby,
    $node->dateidentified,
    $node->collectornumber,
    $node->fieldnumber,
    $node->collector,
    $node->earliestdatecollected,
    $node->latestdatecollected,
    $node->fieldnotes,
    $node->count,
    $node->genbanknum,
    $node->remarks,
    $node->lifestage,
    $node->basisofrecord,
    $node->sex,
    $node->taxonomicname,
    $node->typestatus,
    $node->othercataloguenum,
    $node->locationnode
  );
  // Also need to link the taxonomies to the entry (duplication - FUCK, I know).
  $node->taxonomy = array_merge(is_array($node->taxonomy)?$node->taxonomy:array(),array(
      $node->basisofrecord,
      $node->sex,
      $node->taxonomicname,
      $node->typestatus
    )
  );
}

function darwincorelocation_insert($node){
  $result = db_query("INSERT INTO {darwincorelocation} (nid,vid,islandgroup,island,stateprovince,county,locality,geodeticdatum,verbatimcoordinatesystem,georeferenceprotocol,coordinateuncertainty,georeferenceremarks,minelevation,maxelevation,mindepth,maxdepth,continentocean) VALUES (%d,%d,'%s','%s','%s','%s','%s','%s','%s','%s','%s','%s',%d,%d,%d,%d,%d);",
    $node->nid,$node->vid,
    $node->islandgroup,
    $node->island,
    $node->stateprovince,
    $node->county,
    $node->locality,
    $node->geodeticdatum,
    $node->verbatimcoordinatesystem,
    $node->georeferenceprotocol,
    $node->coordinateuncertainty,
    $node->georeferenceremarks,
    $node->minelevation,
    $node->maxelevation,
    $node->mindepth,
    $node->maxdepth,
    $node->continentocean
  );
  // Also need to link the taxonomies to the entry (duplication - FUCK, I know).
  $node->taxonomy = array_merge(is_array($node->taxonomy)?$node->taxonomy:array(),array($node->continentocean));
}
/**
 * Implementation of hook_update()
 */
function darwincore_update($node){
  if ($node->revision){
    darwincore_insert($node);
  }
  else {
    // Delete then insert (Buggered if this fails!)
    db_query("DELETE FROM {darwincore} WHERE nid = %d and vid = %d",$node->nid, $node->vid);
    darwincore_insert($node);
  }
}
function darwincorelocation_update($node){
  if ($node->revision){
    darwincorelocation_insert($node);
  }
  else {
    // Delete then insert (Buggered if this fails!)
    db_query("DELETE FROM {darwincorelocation} WHERE nid = %d and vid = %d",$node->nid, $node->vid);
    darwincorelocation_insert($node);
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function darwincore_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'delete revision':
      db_query('DELETE FROM {darwincore} WHERE vid = %d', $node->vid);
      break;
    case 'view':
      // Delete the shit that the location module adds.
      unset($node->content['locations']);
      break;
  }
}
function darwincorelocation_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'delete revision':
      db_query('DELETE FROM {darwincorelocation} WHERE vid = %d', $node->vid);
      break;
    case 'view':
      // Delete the shit that the location module adds.
      unset($node->content['locations']);
      break;
  }
}

/**
 * Implementation of hook_delete().
 */
function darwincore_delete($node) {
  db_query('DELETE FROM {darwincore} WHERE nid = %d', $node->nid);
}
function darwincorelocation_delete($node){
  db_query('DELETE FROM {darwincorelocation} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */
function darwincore_load($node) {
  $object = db_fetch_object(db_query('SELECT * FROM {darwincore} WHERE vid = %d', $node->vid));
  // Surely there must be a Drupal way of doing this ugly code.
  $dates = array(&$object->dateidentified,&$object->earliestdatecollected,&$object->latestdatecollected);
  foreach($dates as &$date){
    $date = split('-',$date);
    $date = array('year'=>(int)$date[0],'month'=>(int)$date[1],'day'=>(int)$date[2]);
  }
  // End of the uglyness //
  // If integers, set them to null
  $object->count = ($object->count==0)?'':$object->count;
  return $object;
}
function darwincorelocation_load($node) {
  $object = db_fetch_object(db_query('SELECT * FROM {darwincorelocation} WHERE vid = %d', $node->vid));
  // Surely there must be a Drupal way of doing this ugly code.
  // If integers, set them to null
  $object->minelevation = ($object->minelevation==0)?'':$object->minelevation;
  $object->maxelevation = ($object->maxelevation==0)?'':$object->maxelevation;
  $object->mindepth = ($object->mindepth==0)?'':$object->mindepth;
  $object->maxdepth = ($object->maxdepth==0)?'':$object->maxdepth;
  return $object;
}

function darwincore_submit($form, &$form_state){
  // Set the title to be a concat of other fields
  $form_state['values']['title'] = $form_state['values']['institutioncode']." ".$form_state['values']['collectioncode']." ".$form_state['values']['cataloguenumbertext'];
  // Set the locationnode to be the numeric nid
  
  $darwincorelocation_nodes = db_fetch_array(db_query("SELECT n.nid FROM {node} n, {node_revisions} r WHERE r.vid = n.vid AND r.title = '%s' AND type = 'darwincorelocation'", $form_state['values']['locationnode']));
  
  if(is_array($darwincorelocation_nodes)){

    $form_state['values']['locationnode'] = array_pop($darwincorelocation_nodes);
    
  }
  

}

/**
 * Implementation of hook_form_alter()
 */
function darwincore_form_alter($form, $form_state, &$form_id){
  // Change the locations form element as created by this form and the location module.
  if($form_id == 'darwincore_node_form' || $form_id == 'darwincorelocation_node_form'){
    foreach (_darwincore_get_vids() as $vid){
      unset($form['taxonomy'][$vid]);
    }
    $contains_an_array = false;
    if(isset($form['taxonomy']) && is_array($form['taxonomy'])){
      foreach ($form['taxonomy'] as $taxonomy_part){      
        if(is_array($taxonomy_part)){
          $contains_an_array = true;
        }
      }
    }
    if (!$contains_an_array){
      unset($form['taxonomy']);
    }
    if($form_id == 'darwincore_node_form'){
      unset($form['locations']);
    }
    else{
      /*$form['locations'] = $form['locations'][0];
      $form['locations']['#weight'] = -100;*/
      $form['locations']['#title'] = t('Country and Coordinates');
      $form['locations']['#collapsed'] = 0;
      $form['locations']['#collapsible'] = 0;
      $form['locations']['#weight'] = -100;
    }
  }
  /* First, we ensure the vocabulary called "Taxa" is not visible in the Drupal taxonomy listing because we don't want it to be deleted or modified */
  elseif($form_id == 'taxonomy_overview_vocabularies') {
    $vids = _darwincore_get_vids();
    foreach($vids as $vid){
      unset($form[$vid]);
    }
  }
  // Don't allow editing of darwincore vocabularies
  elseif ($form_id == 'taxonomy_form_vocabulary'){
    if($form['module']['#value'] == 'darwincore' || $form['module']['#value'] == 'darwincorelocation'){
      $vocabulary = check_plain($form['identification']['name']['#default_value']);
      drupal_set_message(t('The %vocabulary vocabulary can not be edited', array('%vocabulary'=>$vocabulary)), 'error');
      drupal_goto('admin/content/taxonomy');
    }
    // Hide Specimen and Location (DwC 1.2.1) From the Content types list
    if($form_id == 'taxonomy_form_vocabulary'){
      unset($form['content_types']['nodes']['#options']['darwincore']);
      unset($form['content_types']['nodes']['#options']['darwincorelocation']);
    }
  }
}

function _darwincore_get_vids(){
  $vid = array();
  $vocabularies = taxonomy_get_vocabularies();
  foreach($vocabularies as $vocabulary){
    if ($vocabulary->module == 'darwincore'||$vocabulary->module == 'darwincorelocation'){
      $vid[] = $vocabulary->vid;
    }
  }
  return $vid;
}

function _darwincore_get_vocabulary_form($vocabulary_name, $default, $description){
  $vocabularies = taxonomy_get_vocabularies();
  foreach($vocabularies as $vocabulary){
    if (($vocabulary->module =='darwincore' || $vocabulary->module =='darwincorelocation') && $vocabulary->name == $vocabulary_name){
      return _taxonomy_term_select($vocabulary_name, "", $default, $vocabulary->vid, $description, false, "--Select--");
    }
  }
}

function _darwincore_get_taxonomicname($name){
  if (is_numeric($name)){
    $term = taxonomy_get_term($name);
    return $term->name;
  }
  else{
    $term = taxonomy_get_term_by_name($name);
    if($term){
      return $term[0]->tid;
    }
    $term_array = db_fetch_array(db_query("SELECT tid FROM {term_synonym} WHERE LOWER(name) = '%s'", strtolower($name)));
    if(is_array($term_array)){
      $term = taxonomy_get_term(array_pop($term_array));
      return $term->tid;
    }
  }    
}
