<?php
// $Id$
/**
 * @file
 * Forces a site to include a footer which can only be changed by editing the source code
 */

/**
 * Removed the following function from the Drupal-5 version of this module.
 * These should be repleced
 * - Hiding of advanced menu items from users
 * - All of the form tidying that cleans up node edit forms
 */

/**
 * Implementation of hook_menu
 */
function scratchpadify_menu(){
  $items = array();
  $items['taskguide'] = array(      
    'title' => 'Task guide',
    'page callback' => 'scratchpadify_taskguide',
    'access arguments' => array('create type content'),
    'type' => MENU_NORMAL_ITEM  
  );
  $items['node'] = array(
    'title' => 'Content',
    'page callback' => 'scratchpadify_node_page_default',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function scratchpadify_node_page_default(){
  $result = pager_query(db_rewrite_sql('SELECT n.nid, n.sticky, n.created FROM {node} n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC'), variable_get('default_nodes_main', 10));

  $output = '';
  $num_rows = FALSE;
  while ($node = db_fetch_object($result)) {
    $output .= node_view(node_load($node->nid), 1);
    $num_rows = TRUE;
  }

  if ($num_rows) {
    $feed_url = url('rss.xml', array('absolute' => TRUE));
    drupal_add_feed($feed_url, variable_get('site_name', 'Drupal') .' '. t('RSS'));
    $output .= theme('pager', NULL, variable_get('default_nodes_main', 10));
  }
  else {
    if(user_access('create type content')){
      $output = scratchpadify_taskguide();
    } else {
      $output = '<div id="first-time" style="background-color:white;border:1px solid #e0e5fb; padding: 20px;">'. t('<h1 class="title">Welcome to your new Scratchpad</h1><p>Once logged-in you\'ll be confronted by our Task guide which will help you get started with your site.</p><p>Further help is available from <a href="http://scratchpads.eu/" target="_blank">http://scratchpads.eu/</a>.</p></div>') .'</div>';
    }
  }
  drupal_set_title('');

  return $output;
  
}

function scratchpadify_taskguide(){
  $output = '<style>
table.tasksguide {
width: 90%;
border: 0;
}
tdeighty {
width: 80px;
}
tdfoureighty {
width: 480px;
}
tr.tasksguideeven td{
font-weight: 900;
font-size: 120%;
}
tr.tasksguideodd td{
padding-left: 20px;
}
table.tasksguide td sup{
padding: 0 5px 0 5px;
}
.greyed{
color: #aaa;
background-color: #f8f8f8;
}
</style>
<h3>Content</h3>
<div align="center">
<table border="0" cellspacing="2" cellpadding="2" class="tasksguide">
  <tbody>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/simplePage.png" alt="" />
      </td>
      <td class="tdfoureighty">Simple Page<sup>1</sup><a href="http://www.editwebrevisions.info/help_page_short" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/simpleMaps.png" alt="" />
      </td>
      <td class="tdfoureighty">Simple Map<sup>1</sup><a href="http://www.editwebrevisions.info/help_map" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty">Create a <a href="/node/add/page">basic page</a></td>
      <td class="tdfoureighty">Create a <a href="/map/macro">basic map</a></td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/forum.png" alt="" />
      </td>
      <td class="tdfoureighty">Forum<sup>1</sup><a href="http://www.editwebrevisions.info/help_forum" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/filestore.png" alt="" />
      </td>
      <td class="tdfoureighty">Filestore<sup>1</sup><a href="http://www.editwebrevisions.info/help_filestore" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty">Post a new <a href="/node/add/forum">forum topic</a>, or <a href="/forum">read the forums</a></td>
      <td class="tdfoureighty"><a href="/node/add/fileshare">Upload</a> a public or private file to the filestore</td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/taxonomy.png" alt="" />
      </td>
      <td class="tdfoureighty">Taxonomy<sup>2</sup><a href="http://www.editwebrevisions.info/help_taxonomy" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/specimens.png" alt="" />
      </td>
      <td class="tdfoureighty">Specimens<sup>2</sup><!--<a href="http://www.editwebrevisions.info/help_specimen" target="_blank">--><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /><!--</a>--></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty"><a href="/admin/content/taxonomy">Create</a> or <a href="/admin/content/taxonomy/import">upload</a> a taxonomic hierarchy</td>
      <td class="tdfoureighty greyed">Create and <!--<a href="/admin/content/node_import">-->upload a list<!--</a>--> or add a <!--<a href="/node/add/specimen">-->single entry<!--</a>--></td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/literature.png" alt="" />
      </td>
      <td class="tdfoureighty">Literature<sup>2</sup><a href="http://www.editwebrevisions.info/help_biblio" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/images.png" alt="" />
      </td>
      <td class="tdfoureighty">Images<sup>2</sup><a href="http://www.editwebrevisions.info/help_images" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty">Upload a <a href="/biblio/import/form">reference list</a> or add a <a href="/node/add/biblio">single entry</a>.</td>
      <td class="tdfoureighty"><a href="/node/754">Upload single or multiple images</a> for annotation.</td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/syndication.png" alt="" />
      </td>
      <td class="tdfoureighty">Syndication (RSS)<sup>2</sup><a href="http://www.editwebrevisions.info/help_syndication" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/customData.png" alt="" />
      </td>
      <td class="tdfoureighty">Custom Data<sup>3</sup><a href="http://www.editwebrevisions.info/help_cck" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty"><a href="/admin/content/aggregator">Add a news feed</a> from another website</td>
      <td class="tdfoureighty"><a href="/admin/content/types/add">Create</a>, <a href="/admin/content/node_import">upload</a> and <a href="/admin/build/views/add">view</a> custom datasets.</td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/dna.png" alt="" />
      </td>
      <td class="tdfoureighty">DNA Sequences<sup>2</sup><!--<a href="http://www.editwebrevisions.info/help_dna" target="_blank">--><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /><!--</a>--></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/genes.png" alt="" />
      </td>
      <td class="tdfoureighty">Genes<sup>2</sup><!--<a href="http://www.editwebrevisions.info/help_gene" target="_blank">--><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /><!--</a>--></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty greyed">Upload DNA sequences or add a single entry</td>
      <td class="tdfoureighty greyed">Add new genes to label DNA sequences</td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/view.png" alt="" />
      </td>
      <td class="tdfoureighty">Template Views<sup>2</sup><a href="http://www.editwebrevisions.info/help_cck_view" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/customView.png" alt="" />
      </td>
      <td class="tdfoureighty">Custom Views<sup>3</sup><a href="http://www.editwebrevisions.info/help_cck_view" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty greyed">Integrate data on a new page with one of our templates</td>
      <td class="tdfoureighty greyed">Create a custom view of your data by creating a new template</td>
    </tr>
  </tbody>
</table>
</div>
<h3>Administration</h3>
<div align="center">
<table border="0" cellspacing="2" cellpadding="2" class="tasksguide">
  <tbody>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/information.png" alt="" />
      </td>
      <td class="tdfoureighty">Site Information<sup>1</sup><a href="http://www.editwebrevisions.info/help_siteinfo" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/profile.png" alt="" />
      </td>
      <td class="tdfoureighty">Your Profile<sup>1</sup><a href="http://www.editwebrevisions.info/help_users" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty">Change the <a href="/admin/settings/site-information">site title, mission statement</a> and <a href="/admin/build/themes">logo</a></td>
      <td class="tdfoureighty"><a href="/user/';
      //dynamically set the ID number of the user logged in 
  global $user;
  $output .= $user->uid .'/edit">Edit your personal information</a>, including <a href="/user/'.$user->uid.'/edit/gmap_user">where you are</a></td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/users.png" alt="" />
      </td>
      <td class="tdfoureighty">Users<sup>1</sup><a href="http://www.editwebrevisions.info/help_users" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/navigation.png" alt="" />
      </td>
      <td class="tdfoureighty">Site Navigation<sup>2</sup><a href="http://www.editwebrevisions.info/help_navigation" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty"><a href="/admin/user/user/create">Add</a>, <a href="/admin/user/user">delete and edit</a> registered users.</td>
      <td class="tdfoureighty">Customize <a href="/admin/build/menu">menus</a>, <a href="/admin/build/block">blocks</a> and <a href="/admin/content/node">all site content</a>.</td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/feedback.png" alt="" />
      </td>
      <td class="tdfoureighty">Feedback<sup>2</sup><a href="http://www.editwebrevisions.info/help_feedback" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/theme.png" alt="" />
      </td>
      <td class="tdfoureighty">Visual Theme<sup>2</sup><a href="http://www.editwebrevisions.info/help_themes" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty"><a href="/admin/content/comment/list/approval">Moderate</a> comments</td>
      <td class="tdfoureighty">Change the <a href="/admin/build/themes">visual theme</a> of your site.</td>
    </tr>
    <tr class="tasksguideeven">
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/backup.png" alt="" />
      </td>
      <td class="tdfoureighty">Backup<sup>1</sup><a href="http://www.editwebrevisions.info/help_backup" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
      <td class="tdeighty" rowspan="2">
      <img src="'.drupal_get_path('module','scratchpadify').'/images/logs.png" alt="" />
      </td>
      <td class="tdfoureighty">Logs<sup>1</sup><a href="http://www.editwebrevisions.info/help_logs" target="_blank"><img src="'.drupal_get_path('module','scratchpadify').'/images/help.png" alt="" /></a></td>
    </tr>
    <tr class="tasksguideodd">
      <td class="tdfoureighty">
      <script type="text/javascript">
      hiddenmail  = \'<a hr\';
      hiddenmail += \'ef="m\';
      hiddenmail += \'ailto\';
      hiddenmail += \':scra\';
      hiddenmail += \'tchpa\';
      hiddenmail += \'d@nhm\';
      hiddenmail += \'.ac.u\';
      hiddenmail += \'k">Co\';
      hiddenmail += \'ntact\';
      hiddenmail += \' us</\';
      hiddenmail += \'a>\';
      document.write(hiddenmail);
      </script> to restore your site from backup.</td>
      <td class="tdfoureighty"><a href="/admin/logs/visitors">Who</a>, <a href="/admin/logs/pages">what</a> and <a href="/admin/logs/search">how</a> users access the site.</td>
    </tr>
  </tbody>
</table>
</div>
<!--break-->
<h3>
User Experience Key
</h3>
<ol>
  <li>None - no experience required</li>
  <li>Limited - basic experience needed</li>
  <li>Advanced - suitable for an experienced user</li>
</ol>';
  return $output;
}

/**
 * Implementation of hook_filter
 */
function scratchpadify_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(0 => t('Script filter'));
    case 'description':
      return t('Strip ALL &lt;script&gt; tags from content');
    case 'prepare':
      // Given we're simply striping, and not replacing anything, it's fine to do it here
      $text = preg_replace('@<[^>]*script.*<[^>]*script[^>]*>@se', '', $text);
      $text = preg_replace('@<[^>]*object.*<[^>]*object[^>]*>@se', '', $text);
      return $text;
    case "process":
      return $text;
    default:
      return $text;
  }
}
/**
 * Implementation of hook_link_alter
 */
function scratchpadify_link_alter(&$links, $node){
  // We need to delete the taxonomy modules created links here.
  drupal_add_css(drupal_get_path('module','scratchpadify').'/scratchpadify.css');
  if(isset($node->taxonomy) && is_array($node->taxonomy)){
    foreach ($node->taxonomy as $term) {
      if(isset($links['taxonomy_term_'. $term->tid])){
        unset($links['taxonomy_term_'. $term->tid]);
      }
    }
  }
}

/**
 * Implementation of hook_link
 */
function scratchpadify_link($type, $node = NULL, $teaser = FALSE){
  // This returns one BIG link which has lots of lickle links in it
  $terms = array();
  if(isset($node->taxonomy) && is_array($node->taxonomy)){
    foreach ($node->taxonomy as $term) {
      if(!isset($terms[$term->vid])){
        $terms[$term->vid] = array();
      }
      $terms[$term->vid][] = $term;
    }
  }
    
  $return_html = '<div class="scratchpadify-terms">';
  $vocabularies = taxonomy_get_vocabularies();
  foreach($terms as $vid => $terms){
    $vocabulary = $vocabularies[$vid];
    $return_html .= '<p><b>'.check_plain($vocabulary->name).':</b> <span>';
    $terms_array = array();
    foreach($terms as $term){
      $terms_array[] = l($term->name,'taxonomy/term/'.$term->tid);
    }
    $return_html .= implode("; ",$terms_array).'</span></p>';
  }
  $return_html .= '</div>';
  $links = array();
  $links[] = array('title' => $return_html , 'html' => true);
  return $links;
}

/**
 * Implementation of hook_footer()
 */
function scratchpadify_footer($main=0){
  // Add the following HTML to the footer of ALL pages
  return '<div id="scratchpadify-footer" align="center" style="padding: 20px"><a 
href="http://e-taxonomy.eu/"><img src="'.base_path().drupal_get_path('module','scratchpadify').'/images/edit_small.png" 
alt="edit logo" style="padding: 0px 30px"/></a><a href="http://scratchpads.eu"/><img alt="Scratchpads logo" style="border-width: 0; padding:10px 30px 0 0" src="'.base_path().drupal_get_path('module','scratchpadify').'/images/scratchpads.png"/></a><a rel="license" 
href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" 
style="border-width: 0pt;" src="'.base_path().drupal_get_path('module','scratchpadify').'/images/cc.logo.1.png"  style="padding: 0px 30px"/></a><a href="http://drupal.org/"><img src="'.base_path().drupal_get_path('module','scratchpadify').'/images/drupal_small.png" alt="drupal logo" style="padding: 0px 30px"/></a>
<!--/Creative Commons License--><!-- <rdf:RDF xmlns="http://web.resource.org/cc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
  <Work rdf:about="">
    <license rdf:resource="http://creativecommons.org/licenses/by-nc-sa/3.0/" />
  <dc:type rdf:resource="http://purl.org/dc/dcmitype/Text" />
  </Work>
  <License rdf:about="http://creativecommons.org/licenses/by-nc-sa/3.0/"><permits rdf:resource="http://web.resource.org/cc/Reproduction"/><permits rdf:resource="http://web.resource.org/cc/Distribution"/><requires rdf:resource="http://web.resource.org/cc/Notice"/><requires rdf:resource="http://web.resource.org/cc/Attribution"/><prohibits rdf:resource="http://web.resource.org/cc/CommercialUse"/><permits rdf:resource="http://web.resource.org/cc/DerivativeWorks"/><requires rdf:resource="http://web.resource.org/cc/ShareAlike"/></License></rdf:RDF> --></div>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
_uacct = "UA-2428547-2";
urchinTracker();
</script><div style="display:none">Scratchpads developed and conceived by: <a href="http://vsmith.info/">Vince Smith</a>, <a href="http://simon.rycroft.name">Simon Rycroft</a> & Dave Roberts</div>';
}

/**
 * Implementation of hook_block().
 *
 */
function scratchpadify_block($op = 'list', $delta = 0, $edit = array()){
  switch ($op){
    case 'list':
      return array(array('info'=>t('Scratchpad statistics')),array('info'=>t('Create Content')),array('info'=>t('About this site')));
    case 'view':
      switch($delta){
        case 0:
          $nodes = db_fetch_array(db_query("SELECT COUNT(nid) AS nodes FROM node;"));
          $users = db_fetch_array(db_query("SELECT COUNT(uid) AS users FROM users"));
          $views = db_fetch_array(db_query("SELECT SUM(totalcount) AS totalcount FROM node_counter;"));
          $items = array('Pages: '.$nodes['nodes'],'Users: '.($users['users']-2),'Total Page Views: '.$views['totalcount']);
          return array('subject'=>'Statistics','content'=>theme_item_list($items));
        case 1:
          if(user_access('create node content')){
            drupal_add_css(drupal_get_path('module','scratchpadify').'/scratchpadify.css');
            $node_types = node_get_types();
            $items = array();
            foreach($node_types as $node_type => $node_type_values){
              $items[$node_type_values->name] = l($node_type_values->name,'node/add/'.$node_type);
            }
            $items[t('Import bibliography')] = l(t('Import bibliography'), 'biblio/import/form');
            $items[t('Create/Edit Taxonomy')] = l(t('Create/Edit Taxonomy'), 'admin/content/taxonomy');
            ksort($items);
            return array('subject'=>'Create Content','content'=>theme_item_list($items , NULL , 'ul' , array('class'=>'scratchpadify-block')));
          }
          break;
        case 2:
          $uid = array_pop(db_fetch_array(db_query("SELECT uid FROM users WHERE uid > 1 ORDER BY uid ASC LIMIT 1")));
          $maintainer = user_load(array('uid'=>$uid));
          return array('subject'=>'About this site','content'=>'<p>This site is moderated by <span style="text-decoration:underline">'.$maintainer->name.'</span> on behalf of the  contributors who retain copyright.</p><p>Content can be used in accordance with a <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/">CC Licence</a>.</p><p>This site uses <a href="http://drupal.org">Drupal</a> and is based on a set of templates and modules defined by the <a href="http://scratchpads.eu/">Scratcpad</a> team at the Natural History Museum, London.</p>');
      }
      break; 
    case 'configure': // No need to add any extra configuration - Open to suggestions.
      if($delta == 0){
        $form['additional_text']=array(
          '#description' => t('Enter any additional text you would like above the statistics.'),
          '#title' => t('Additional text'),
          '#type' => 'textfield',
          '#weight' => -9,
          '#default_value' => variable_get('scratchpadify-stats-block-text','')
        );
        return $form;
      }
    case 'save':
      if($delta == 0){
        variable_set('scratchpadify-stats-block-text', $edit['additional_text']);
      }
  }
}