<?php
/* $Id$ */

/** 
 * @file taxtab.module
 * Provides a block for displaying a taxonomy allowing users to easily browse by their classifications
 */

/**
 * Implementation of hook_form_alter()
 */
function taxtab_form_alter(&$form, &$form_state, $form_id){
  if ('search_block_form' == $form_id) {
    $form['tabs'] = _taxtab_tabs(true);
    unset($form['basic']['#title']);
    
    // This doesn't seem logical placing this here, but hey ho!
    drupal_add_js(drupal_get_path('module','taxtab').'/taxtab.js');
    // This may not be included already, so lets ensure it is.
    drupal_add_js('misc/autocomplete.js');
  }
}

/**
 * Implementation of hook_menu, for the callbacks!
 */
function taxtab_menu(){
  $items = array();
  $items['taxtab/normal'] = array(
    'title' => 'search tab',
    'access arguments' => array('search content'),
    'type' => MENU_CALLBACK,
    'page callback' => 'taxtab_normal_js');
  $items['taxtab/taxonomy'] = array(
    'access arguments' => true, 
    'title' => 'search tab',
    'page callback' => 'taxtab_taxonomy_js',
    'type' => MENU_CALLBACK);  
  $items['taxtab/autocomplete'] = array(
    'title' => 'Autocomplete taxtab query',
    'page callback' => 'taxtab_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK);
  $items['taxtab/process'] = array(
    'title' => 'Process form entry',
    'page callback' => 'taxtab_process',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK);
  return $items;  
}
/**
 * Simple helper function to ensure no repetition!
 *
 */
function _taxtab_tabs($taxonomy=false){
  $value = '<div class="taxtab">';
  if ($taxonomy){ $value .= '<b>'; }
  $value .= l("Simple", 'taxtab/normal', array('attributes' => array('class'=>'taxtablink'))).' | ';
  if ($taxonomy){ $value .= '</b>';}
  else {$value .= '<b>';}
  $value .= l("Taxonomy", 'taxtab/taxonomy', array('attributes' => array('class'=>'taxtablink')));
  if (!$taxonomy){$value .= '</b>';}
  $value .= '</div>';
  return array(
    '#value' => $value,
    '#weight' => -10000
  );
}

function taxtab_create_form(&$form_state){
/* TODO drupal_retrieve_form() now accepts a form_state parameter. */
  $form = drupal_retrieve_form('search_form', $form_state);
  $form['basic']['tabs'] = _taxtab_tabs(false);
  $form['basic']['inline']['keys']['#autocomplete_path'] = 'taxtab/autocomplete';
  $form['basic']['inline']['keys']['#size'] = 15;
  $form['#action']='/taxtab/process';
  unset($form['basic']['#title']);
  return $form;
}

/**
 * Implementation of hook_form_validate()
 */
function taxtab_process(){
  if(arg(2)!=''){
    $searchterm = addslashes(str_replace("_"," ",arg(2)));
  } else {
    $searchterm = addslashes($_POST['keys']);// FIXME, not so keen on this.
  }
  $term = taxonomy_get_term_by_name($searchterm);
  if (count($term)>0){
    drupal_goto('taxonomy/term/'.$term[0]->tid);
  }
  drupal_goto('search/node/'.$searchterm);
}

/**
 * Callback for taxtab/taxonomy
 */
function taxtab_taxonomy_js(){
  print drupal_to_js(array('html' => drupal_get_form('taxtab_create_form')));
  exit();
}

/**
 * Callback for taxtab/normal
 */
function taxtab_normal_js(){
  print drupal_to_js(array('html' => drupal_get_form('search_block_form')));
  exit();
}

/**
 * Menu callback to autocomplete a query.
 * 
 * This function is taken directly from tql.module, but changed slightly to suit our needs.
 * - Remove $vid
 * - Removed %% from search to ensure matches are added as typed i.e bar doesn't match foobar.
 *
 * @param $string
 *   The query for which autocompletion should be done.
 */
function taxtab_autocomplete($string = '') {
  $results;
  if(function_exists('leftandright_get_tree')){
    $result = db_query_range(db_rewrite_sql("SELECT t.tid, t.name FROM {term_data} t, {leftandright} l WHERE lowername LIKE LOWER('%s%%') AND l.tid = t.tid ORDER BY t.name", 't', 'tid'), $string, 0, 15);    
  } else {
    $result = db_query_range(db_rewrite_sql("SELECT t.tid, t.name FROM {term_data} t WHERE LOWER(t.name) LIKE LOWER('%s%%') ORDER BY t.name", 't', 'tid'), $string, 0, 15);
  }
  // Construct response array
  $matches = array();
  while ($tag = db_fetch_object($result)) {
    $name = $tag->name;
    // Array key is for textfield, array value for display
    $matches[$prefix . $name] = check_plain($tag->name);
  }
  // Return matches as javascript array
  print(drupal_to_js($matches));
  exit();
}