<?php

/**
 * Implements hook_perm()
 */
function scratchpads_messages_server_perm(){
  return array(
    'addminister scratchpads messages'
  );
}

/**
 * Implements hook_menu().
 */
function scratchpads_messages_server_menu(){
  return array(
    'messages' => array(
      'title' => 'Scratchpads messages',
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'scratchpads_messages_server_list_messages'
      ),
      'access arguments' => array(
        'addminister scratchpads messages'
      )
    ),
    'messages/add' => array(
      'title' => t('Add'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'scratchpads_messages_server_add_messages'
      ),
      'access arguments' => array(
        'addminister scratchpads messages'
      ),
      'type' => MENU_LOCAL_TASK
    ),
    'messages/list' => array(
      'title' => t('List'),
      'type' => MENU_DEFAULT_LOCAL_TASK
    ),
    'messages/list.json' => array(
      'title' => '',
      'page callback' => 'scratchpads_messages_server_list_messages_json',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK
    )
  );
}

/**
 * List the messages callback.
 */
function scratchpads_messages_server_list_messages(){
  return array();
}

/**
 * Add a message callback.
 */
function scratchpads_messages_server_add_messages(){
  return array();
}

/**
 * JSON callback.
 */
function scratchpads_messages_server_list_messages_json(){
  return '';
}