<?php 

/**
 * Regally module provides themed views for producing a gallery interface.
 * 
 * This module has been inspired by the image_gallery component of the image
 * module.
 */

/**
 * hook_term_path
 */
function regally_term_path($term){
  // We'll change the path for a gallery term so that using the standard menu
  // structure, we can easily override the way the page is displayed.
  return 'gallery/'.$term->tid;
}

/**
 * hook_menu
 */
function regally_menu(){
  return array(
    'gallery' => array(
      'title' => 'Gallery',
      'description' => 'Gallery page',
      'page callback' => 'regally_page',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'file' => 'regally.page.inc'
    )
  );
}

/**
 * hook_init
 */
function regally_init(){
  // Here we add the CSS, only when required.  This is where any JavaScript 
  // should be added if also required (Future proof!)
  if(arg(0) == 'gallery'){
    drupal_add_css(drupal_get_path('module', 'regally').'/regally.css');
  }
}

/**
 * hook_views_api
 */
function image_gallery_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'regally').'/views'
  );
}

/**
 * hook_imagecache_default_presets
 */
function scratchpadify_imagecache_default_presets(){
  return array(
    'thumbnail' => array(
      'presetname' => 'thumbnail',
      'actions' => array(
        array (
          'weight' => '0',
          'module' => 'imagecache',
          'action' => 'imagecache_scale',
          'data' => array (
            'width' => '100',
            'height' => '100',
            'upscale' => 1,
          )
        )
      )
    ),
    'preview' => array(
      'presetname' => 'preview',
      'actions' => array(
        array (
          'weight' => '0',
          'module' => 'imagecache',
          'action' => 'imagecache_scale',
          'data' => array (
            'width' => '800',
            'height' => '600',
            'upscale' => 0,
          )
        )
      )
    )
  );
}