<?php

/**
 * Implementation of hook_export_publication().
 */
function pensoft_publication_info() {  
  return array(
    'name' => 'Pensoft',
    'description' => 'Export to the Sofia based publisher of ZooKeys and PhytoKeys'
  );  
}

function pensoft_form_publication_export_form_alter($form, $form_state, $form_id){
  if(isset($form_state['post']['module']) && $form_state['post']['module'] == 'pensoft'){
    if(isset($form['#validate'])){
      $form['#validate'][] = 'pensoft_publication_export_form_validate';
    } else {
      $form['#validate'] = array('pensoft_publication_export_form_validate');
    }
    $form['pensoft'] = array(
      'vat_number' => array(
        '#type' => 'textfield',
        '#title' => t('VAT number'),
        '#required' => TRUE,
        '#description' => '('.t('If present, for EU customers only.').')',
      ),
      'notes' => array(
        '#type' => 'textarea',
        '#title' => t('Your notes'),
      )
    );
  }
}

function pensoft_publication_export_form_validate($form, &$form_state){
  if(!is_numeric($form_state['values']['vat_number'])){
    form_set_error('vat_number', t('Must be numeric'));
  }
}

function pensoft_publication_export_form_submit($form, &$form_state){
  
}