<?php

// $Id: content_taxonomy_options.module,v 1.1.4.7.2.4 2008/12/27 11:25:27 mh86 Exp $

/**
 * @file
 * Defines a widget type for content_taxonomy for options
 **/

/**
 * Implementation of hook_theme().
 */
function content_taxonomy_options_theme() {
  return array(
    'content_taxonomy_options_widgets_none' => array(
      'arguments' => array('field' => NULL),
    ),
  );
}

/**
 * Implementation of hook_widget_info().
 */
function content_taxonomy_options_widget_info() {
  return array(
    'content_taxonomy_options' => array(
      'label' => t('Checkboxes/Radios'),
      'field types' => array('content_taxonomy'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
    'content_taxonomy_select' => array(
      'label' => t('Select List'),
      'field types' => array('content_taxonomy'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
  return $items;
}

/**
 * Implementation of hook_widget().
 */
function content_taxonomy_options_widget(&$form, &$form_state, $field, $items, $delta = NULL) {
  $element = array(
    '#type' => ($field['widget']['type'] == 'content_taxonomy_select') ? 'optionwidgets_select' : 'optionwidgets_buttons', 
    '#default_value' => !empty($items) ? $items : array(),
  );
  return $element;
}

/**
 *  Theme the label for the empty value for options (for optional radios and single selects).
 */
function theme_content_taxonomy_options_widgets_none($field) {
  switch ($field['widget']['type']) {
    case 'content_taxonomy_options':
      return t('N/A');
    case 'content_taxonomy_select':
      return t('- None -');
    default :
      return '';
  }
}
