<?php 

define('EOL_IMPORT_QUERY_URL', 'http://services.eol.org/lifedesk/service.php?function=search&search=');
define('EOL_IMPORT_REQUEST_URL', 'http://services.eol.org/lifedesk/service.php?function=details_tcs&id=');

/**
 * Implementation of hook_classification_import_form
 */
function eol_import_classification_import_form(){
  drupal_add_css(drupal_get_path('module','eol_import').'/eol_import.css');
  return array(
    'eol' => array(
      '#type' => 'fieldset',
      '#title' => 'EOL',
      '#description' => 'Import a classification directly from EOL',
      '#collapsed' => TRUE,
      '#collapsible' => TRUE,
      'eol-name' => array(
        '#type' => 'textfield',
        '#title' => t('Enter the root term of your classification, e.g. Phthiraptera, Insecta, Aves'),
        '#autocomplete_path' => 'eol_import'
      ),
      'eol-search' => array(
        '#type' => 'button',
        '#value' => 'Search',
        '#title' => 'Search',        
        '#ahah' => array(
          'path' => 'eol_import',
          'event' => 'click',
          'wrapper' => 'eol-import-full'
        )
      ),
      'import-full' => array(
        '#prefix' => '<div id="eol-import-full">',
        '#suffix' => '</div>',
        '#value' => '&nbsp;'
      ),
      'submit' => array(
        '#type' => 'submit',
        '#title' => t('Import from EOL'),
        '#value' => t('Import from EOL'),
        '#submit' => array('eol_import_submit'),
        '#validate' => array('eol_import_validate')
      )
    )
  );
}

/**
 * Implementation of hook_menu
 */
function eol_import_menu(){
  return array(
    'eol_import' => array(
      'title' => 'EOL Import autocomplete path',
      'page callback' => 'eol_import_autocomplete',
      'access arguments' => array('administer taxonomy'),
      'type' => MENU_CALLBACK
    )
  );
}

/**
 * Callback for autocomplete and ahah.
 */
function eol_import_autocomplete(){
  if(isset($_POST['eol-name'])){
    $eol_xml = file_get_contents(EOL_IMPORT_QUERY_URL.urlencode($_POST['eol-name']));
    if($eol_xml){
      $eol_xml = new SimpleXMLElement($eol_xml);
      $num_results = count($eol_xml->value);
      $options = array();
      for($i = 0; $i < $num_results; $i++){
        $options[check_plain($eol_xml->value[$i]->id)] = check_plain($eol_xml->value[$i]->ancestry .'|'. $eol_xml->value[$i]->name) . " <br/>(" . l($eol_xml->value[$i]->metadata->title, $eol_xml->value[$i]->metadata->url, array('abosulte' => 1)).')';
      }
    }
    $form['eol-import-id'] = array(
      '#type' => 'radios',
      '#name' => 'eol-import-id',
      '#title' => t('Import from Classification'),
      '#default_value' => '',
      '#parents' => array('eol-import-id'),
      '#options' => $options
    );
    // FIXME - Looks like the following is hacky (probably not correct).
    $form['eol-import-id'] = expand_radios($form['eol-import-id']);
    $keys = element_children($form['eol-import-id']);
    foreach($keys as $key){
      $form['eol-import-id'][$key]['#name'] = 'eol-import-id';
    }
    // Now we're right.
    drupal_json(array('status' => TRUE, 'data' => drupal_render($form)));  
    return;
  } elseif(arg(1)) {
    $eol_xml = file_get_contents(EOL_IMPORT_QUERY_URL.urlencode(arg(1)));
    if($eol_xml){
      $eol_xml = new SimpleXMLElement($eol_xml);
      $num_results = count($eol_xml->value);
      $matches = array();
      for($i = 0; $i < $num_results; $i++){
        $name = $eol_xml->value[$i]->canonical_form;
        $matches[check_plain($name)] = check_plain($name);
      }
      echo json_encode($matches);
      return;
    }
  }
  echo json_encode(array());
}

/**
 * Implementation of hook_classification_import_help
 */
function eol_import_classification_import_help(){
  return t('EOL import help text.');
}

/**
 * Validate the form
 */
function eol_import_validate($form, &$form_state){
  // Lets just check that the eol-import-id is set in #post, and that it is
  // numeric (is this likely to change Patrick?).
  if(!(isset($form_state['clicked_button']['#post']['eol-import-id']) && is_numeric($form_state['clicked_button']['#post']['eol-import-id']))){
    form_set_error('eol-name', t('Please ensure you select a classification to import.  Press "Search" again, and select one from the list that should appear below.'));
  }
}

/**
 * Callback function when pressing "Import from EOL"
 */
function eol_import_submit($form, $form_state){
  $batch = array(
    'operations' => array(
      array('tcs_import_batch_download_data', array(array(EOL_IMPORT_REQUEST_URL.$form_state['clicked_button']['#post']['eol-import-id']), arg(4))),
      array('classification_import_load_terms', array(arg(4)))
    ),
    'finished' => 'classification_import_batch_import_finished',
    'title' => t('Importing'),
    // We use a single multi-pass operation, so the default
    // 'Remaining x of y operations' message will be confusing here.
    'error_message' => t('The import has encountered an error.')
  );
  batch_set($batch);
}