<?php
// $Id: xmlsitemap_menu.module,v 1.1.2.3 2008/06/12 02:31:30 darrenoh Exp $

/**
 * @file
 * Adds menu items to the site map.
 */

/**
 * @addtogroup xmlsitemap
 * @{
 */

/**
 * Implementation of hook_xmlsitmap_links().
 */
function xmlsitemap_menu_xmlsitemap_links($type = NULL, $excludes = array()) {
  if (!isset($type)) {
    unset($GLOBALS['_menu']);
    $menu = menu_get_menu();
    $mid = db_result(db_query_range("SELECT mid FROM {menu} WHERE pid = 0 AND title = '%s'", t('XML Sitemap'), 0, 1));
    $menus = $mid === FALSE ? array() : array($mid);
    $menus = variable_get('xmlsitemap_menu_menus', $menus);
    foreach ($menus as $mid) {
      if (!empty($mid)) {
        _xmlsitemap_menu_process_link($mid, $menu);
      }
    }
  }
}

/**
 * Add links for a menu item and all its children to the site map.
 * @param $mid: The ID of the menu to process
 * @param $menu: The full menu structure for a user
 * @return None
 */
function _xmlsitemap_menu_process_link($mid, $menu) {
  $item = $menu['visible'][$mid];
  if (!empty($item['path']) && strpos($item['path'], '://') === FALSE && $item['path'] != variable_get('site_frontpage', 'node')) {
    $alias = db_result(db_query_range("SELECT dst FROM {url_alias} WHERE src = '%s'", $item['path'], 0, 1));
    $alias = $alias === FALSE ? NULL : $alias;
    $priority = round($menu['items'][$mid]['weight'] / 20 + 0.5, 1);
    $priority = $priority < 0 ? 0 : $priority;
    $priority = $priority > 1 ? 1 : $priority;
    $link = array(
      'loc' => xmlsitemap_url($item['path'], $alias, NULL, NULL, TRUE),
      'priority' => $priority,
    );
    db_query("INSERT INTO {xmlsitemap} (loc, priority) VALUES ('%s', %f)", $link);
  }
  foreach ($item['children'] as $mid) {
    _xmlsitemap_menu_process_link($mid, $menu);
  }
}

/**
 * Implementation of hook_form_alter().
 */
function xmlsitemap_menu_form_alter($form_id, &$form) {
  switch ($form_id) {
    case 'xmlsitemap_settings_sitemap':
      $mid = db_result(db_query_range("SELECT mid FROM {menu} WHERE pid = 0 AND title = '%s'", t('XML Sitemap'), 0, 1));
      $menus = $mid === FALSE ? array() : array($mid);
      $form['xmlsitemap_menu_menus'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Menus to include in site map'),
        '#default_value' => variable_get('xmlsitemap_menu_menus', $menus),
        '#options' => menu_get_root_menus(),
      );
      $form['buttons']['#weight'] = 1;
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function xmlsitemap_menu_menu($may_cache) {
  if ($may_cache) {
    global $user;
    if (!empty($user->uid)) {
      xmlsitemap_update_sitemap();
    }
  }
}

/**
 * @} End of "addtogroup xmlsitemap".
 */

