<?php
//$Id $
/**
 * @file
 * views_json.module - provides Views plugin for rendering node content as JSON.
 */

/**
 * Implementation of hook_views_style_plugins
 * @return array with style plugin declarations. 
 */
function views_json_views_style_plugins() {
  return array(
    'views_json_exhibit' => array(
      'name' => t('Views JSON: MIT Simile/Exhibit JSON data document'),
      'theme' => 'views_json_exhibit',
      'needs_table_header' => TRUE,
      'needs_fields' => TRUE,
      'even_empty' => TRUE,
    ),
  );
}

/*
 * Implementation of hook_views_arguments to add the Canonical JSON and
 * and Exhibit JSON argument selectors.
 * @returns array of arguments
 */ 
function views_json_views_arguments() {
  $arguments = array(
    'json_exhibit' => array(
      'name' => t('Views JSON: MIT Simile/Exhibit JSON data document selector'),
      'handler' => 'views_json_views_handler',
      'option' => 'string',
      'help' => t('This argument specifies a document selector; it will only provide a method for rendering the current view as JSON.'),
    ),
  );
  return $arguments;
}

/**
 * handler for our own Exhibit JSON argument handler
 */
function views_json_views_handler($op, &$query, $argtype, $arg='') {
  if ($op == 'filter') {
    views_json_views_argument('argument', $GLOBALS['current_view'], $arg);
  }
}

/**
 * argument hook that will display the JSON data document or display export icons.
 */
function views_json_views_argument($op, &$view, $arg) {
  if ($op == 'argument' && ($arg == 'json_exhibit')) {
    $view->page_type = 'views_'. $arg;
  }
  else if ($op == 'post_view' && $view->build_type != 'block') {
    $args = views_post_view_make_args($view, $arg, $arg);
    $url = views_get_url($view, $args);
    $title = views_get_title($view, 'page', $args);
    $links = array();
   
    if ($arg == 'json_exhibit') {
      if (($image = theme('image', drupal_get_path('module', 'views_json') .'/json32x32.png', t('Exhibit JSON'), t('Show @title as MIT Simile/Exhibit JSON', array('@title' => $title))))) {
        $links[] = l($image, $url, array('class' => 'json-icon'), $url_filter, NULL, FALSE, TRUE);
      return implode('&nbsp;&nbsp;', $links);
      }
    }
  }
    
}

/*
 * describes how to theme a Exhibit JSON view
 */
function theme_views_json_exhibit($view, $nodes, $type) {
  views_json_exhibit_render($view->vid, $nodes, $type);
}

/**
 * post view to display the render icons
 */
function views_json_views_post_view($view, $items, $output) {
  $links = '';
  foreach ($view->argument as $id => $argument) {
    if ($argument['type'] == 'json_exhibit') {
      $links .= views_json_views_argument('post_view', $view, $argument['type'], '');
    }
  }
  return $links;
}

function views_json_exhibit_render($vid, $nodes, $type) {
  define('EXHIBIT_DATE_FORMAT', '%Y-%m-%d %H:%M:%S');
  $view = views_load_view($vid);
  $result = views_build_view('items', $view);
  $fields = _views_get_fields();
  
  $items = array();
  $view_properties = array ();
  $json = "{\n".str_repeat(" ", 4).'"items"'." : ". "  [";
  foreach ($nodes as $node) {
   /*$items[] = array(
     'type'        => $node->type,
     'id'          => 'node/' . $node->nid,
     'label'       => $node->title,
     'author'      => 'user/' . $node->uid,
     'created'     => gmstrftime(EXHIBIT_DATE_FORMAT, $node->created),
     'changed'     => gmstrftime(EXHIBIT_DATE_FORMAT, $node->changed),
     'body'        => $node->teaser,
     'url'         => url('node/' . $node->nid, array('absolute' => TRUE)),
   );*/
   $json.="\n".str_repeat(" ", 8)."{\n";
   foreach ($view->field as $field) { 
    if ($fields[$field['id']]['visible'] !== false) {
        $label = $field['label'] ? $field['label'] : $fields[$field['fullname']]['name'];
        $value = $field;
        $value = views_theme_field('views_handle_field', $field['queryname'], $fields, $field, $node, $view);
        $value = preg_replace('/<.*?>/', '', $value); // strip html tags
        $value = str_replace(array("\r", "\n", ','), ' ', $value); // strip line breaks and commas
        $value = str_replace(array(':', '#', '/',),'', $value); //strip special javascript characters
        $label = str_replace(array(':', '#', '/',),'', $label); //strip special javascript characters
        $value = str_replace('"', '""', $value); // escape " characters
        $value = decode_entities($value);
        $json.=str_repeat(" ", 8).$label. " ".": ".'"'.$value.'"'."\n";
    }    
   }
   $json.=str_repeat(" ", 8)."},\n";
  }
  $json.=str_repeat(" ", 4)."]\n}";
// $types  = array('node' => array('label' => t('Node'), 'pluralLabel' => t('Nodes')));
// $properties = array(
//   'author'     => array('valueType' => 'item'),
//   'created'    => array('valueType' => 'date'),
//   'changed'    => array('valueType' => 'date'),
//   'url'        => array('valueType' => 'url'),
// );
//  $exhibit_json = array(
//   'items'      => $items,
//   'types'      => $types,
//   'properties' => $properties,
// );
//return drupal_to_js($exhibit_json);
//print_r($items);

drupal_set_header('Content-Type: text/javascript');
print $json;
module_invoke_all('exit');
exit;
}