<?php

/**
 * @file
 *
 * This is the module file for the citation module.
 * 
 * The module defines it own hook which is used to add additional data to a
 * citation for a page.  This is mainly used so that the externally loaded
 * content can add its own citations.  The hook is called "hook_citation"
 * 
 * hook_citation(&$citations = array(), &$javascript = FALSE)
 */

/**
 * Implementation of hook_menu
 */
function citation_menu(){
  $items = array();
  $items['citation/create_no_js'] = array(
    'title' => '',
    'page callback' => 'citation_create_no_js',
    'type' => MENU_CALLBACK,
    'access arguments' => array('create citations'),
  );
  $items['citation/get_citations'] = array(
    'title' => '',
    'page callback' => 'citation_get_citations',
    'type' => MENU_CALLBACK,
    'access arguments' => array('create citations')
  );
  return $items;
}

/**
 * Creates a page for users without JS.
 */
function citation_create_no_js(){
}

/**
 * Callback to return the ajax for citations
 */
function citation_get_citations(){
  global $_SESSION;
  $citations = array();
  if(isset($_SESSION['citation'][$_GET['page']]['urls']) && is_array($_SESSION['citation'][$_GET['page']]['urls'])){
    foreach($_SESSION['citation'][$_GET['page']]['urls'] as $url_array){
      $citations[] = theme('citation_url', $url_array);
    }
  }
  if(isset($_SESSION['citation'][$_GET['page']]['nids']) && is_array($_SESSION['citation'][$_GET['page']]['nids']) && count($_SESSION['citation'][$_GET['page']]['nids'])){
    $results = db_query("SELECT DISTINCT uid FROM {node_revisions} WHERE nid IN (%s)", implode(",",$_SESSION['citation'][$_GET['page']]['nids']));
    while($row = db_fetch_array($results)){
      $user = user_load($row['uid']);
      $citations[] = l(theme('citation_user',$user),'user/'.$user->uid);      
    }
  }
  unset($_SESSION['citation'][$_GET['page']]);
  if(count($citations)){
    $output = theme('citations',$citations).'<p>'.l('Create Citation','citation/create_no_js',array('attributes' => array('onclick'=>'citation_create();return false;'))).'</p>';   
  } else {
    $output = t('We have no information about the Authors and Sources on this page');
  }
  print json_encode(array('content' => $output));
  exit;
}

/**
 * Implementation of hook_perm
 */
function citation_perm(){
  return array('create citations');
}

/**
 * Implementation of hook_theme
 */
function citation_theme() {
  return array(
    'citations' => array(
      'arguments' => array('citations' => array()),
    ),
    'citation_user' => array(
      'arguments' => array('user' => NULL)
    ),
    'citation_url' => array(
      'arguments' => array('urls' => array())
    )
  );
}

/**
 * Adds any nodes nid which is being "VIEWED".
 * 
 * Implementation of hook_nodeapi
 */
function citation_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
  if($op == 'view'){
    citation_add_nid($node->nid);
  }
}

/**
 * Adds any nodes nid which is being "VIEWED" as part of a view.
 *
 * Implementation of hook_views_pre_execute
 */
function citation_views_pre_execute(&$view){
  $query = db_rewrite_sql($view->build_info['query'], $view->base_table, $view->base_field, array('view' => &$view));
  $args = $view->build_info['query_args'];
  $replacements = module_invoke_all('views_query_substitutions', $view);
  $query = str_replace(array_keys($replacements), $replacements, $query);     
  if (is_array($args)) {
    foreach ($args as $id => $arg) {
      $args[$id] = str_replace(array_keys($replacements), $replacements, $arg);
    }
  }
  $result = db_query_range($query, $args, 0, $view->pager['items_per_page']);
  while($row = db_fetch_array($result)){
    if(isset($row['nid'])){
      citation_add_nid($row['nid']);
    }
  }
}

/**
 * Add the nid to a global variable
 */
function citation_add_nid($nid, $url = false){
  global $_SESSION;
  if(!$url){
    $url = request_uri();
  }
  $_SESSION['citation'][$url]['nids'][$nid] = $nid;
}

/**
 * Add the URL to a global variable
 */
function citation_add_url($url_array, $url = false){
  global $_SESSION;
  watchdog('citation', 'Setting URL');
  if(!$url){
    $url = request_uri();
  }
  if(strpos($url, "http")===0){
    $url = substr($url, strpos($url, "/", 10));
  }
  watchdog('citation', 'URL is: '.print_r($url, true));
  watchdog('citation', 'URL array is: '.print_r($url_array, true));
  $_SESSION['citation'][$url]['urls'][$url_array['name']] = $url_array;
  watchdog('citation', print_r($_SESSION['citation'], true));  
}

/**
 * Implementation of hook_block
 */
function citation_block($op = 'list', $delta = 0, $edit = array()){
  $blocks = array();
  switch($op){
    case 'list' :
      $blocks[] = array(
        'info' => t('Authors & Sources'),
        'description' => t('A generated list of all authors and sources for the page being viewed.'),
        'cache' => BLOCK_NO_CACHE
      );
      break;
    case 'view' :
      if(user_access('create citations')){
        drupal_add_js(drupal_get_path('module', 'citation').'/citation.js');
        $blocks = array(
          'title' => t('Authors & Sources'),
          'content' => '<div id="citation"><script type="text/javascript">citation_get_citations(\''.url('citation/get_citations',array('absolute'=>TRUE, 'query'=>array('page' => request_uri()))).'\');</script></div>'
        );
      }
      break;
  }
  return $blocks;
}

function theme_citation_url($url_array){
  $output = l($url_array['name'], $url_array['url']);
  $urls = array();
  $i = 1;
  foreach($url_array['urls'] as $url){
    $urls[] = l($i, $url);
    $i ++;
  }
  $output .= " (". implode(", ", $urls).")";
  return $output;
}

function theme_citation_user($user){
  if(is_object($user)){
    if(isset($user->family_name) && isset($user->given_names)){
      $given_names = explode(" ",$user->given_names);
      $initials = array();
      foreach($given_names as $name){
        $initials[] = strtoupper(substr($name,0,1)).".";
      }
      return $user->family_name .", ".implode(" ",$initials);
    } else {
      return $user->name;
    }
  }
}

function theme_citations($citations){
  return "<ul><li>".implode("</li><li>",$citations)."</li></ul>";
}