<?php

/**
 * @file
 * 
 * This module defines whether or not a Drupal site is a Scratchpad.  By
 * enabling this module, you are consenting to the use of statistics from your
 * site being used by the Scratchpad team for promotion of the Scratchpads.
 * 
 * This module does the following:
 * 
 * - Reports back to dev.scratchpads.eu statistics about this site.
 * - Adds the Scratchpad Google analytics code to the footer of your site.
 * - Adds a page to the site "/scratchpads" which lists all other Scratchpads.
 */
/**
 * Implementation of hook_form_FORM_ID_alter
 */
function scratchpad_form_user_login_alter(&$form, &$form_state){
  // We need to check here to see if we have the nice stuff being returned by
  // an openid login
  if(isset($_GET['uid']) && isset($_GET['openid_mode'])){
    module_load_include('login.inc', 'scratchpad');
    scratchpad_do_openid_login($_GET['uid']);
  }
  // If we're offline, then we need to add the logins form elements to the user
  // form, as otherwise we can't login to help peeps.
  if(variable_get('site_offline', 0)){
    module_load_include('login.inc', 'scratchpad');
    $logins_form = scratchpad_logins();
    // Change the name of the logins button, so that we can tell which button
    // has been pressed.
    $logins_form['submit-logins'] = $logins_form['submit'];
    $logins_form['submit-logins']['#value'] = t('Logins login');
    unset($logins_form['submit']);
    $form['logins'] = array(
      '#weight' => 10,
      '#title' => t('Scratchpad Team Logins'),
      '#type' => 'fieldset',
      '#collapsed' => TRUE,
      '#collapsible' => TRUE,
      $logins_form
    );
    // We need to add a validation step which comes before the standard
    // validation step
    $form['#validate'] = array_merge(array(
      'scratchpad_logins_validate'
    ), $form['#validate']);
  }
}

/**
 * Implementation of hook_perm().
 */
function scratchpad_perm(){
  return array(
    'view scratchpad data'
  );
}

/**
 * Scratchpad validate
 */
function scratchpad_logins_validate($form, &$form_state){
  if($form_state['values']['submit-logins'] == $form_state['clicked_button']['#value']){
    // Skip validation, as Logins requires no validation at this stage.
    scratchpad_logins_submit();
  }
}

/**
 * Implementation of hook_menu
 */
function scratchpad_menu(){
  return array(
    'logins' => array(
      'title' => t('Scratchpad login'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'scratchpad_logins'
      ),
      'access arguments' => array(
        'access content'
      ),
      'type' => MENU_CALLBACK,
      'file' => 'scratchpad.login.inc'
    ),
    'logins/return/%' => array(
      'title' => t('Scratchpad login'),
      'page callback' => 'scratchpad_do_openid_login',
      'page arguments' => array(
        2
      ),
      'access arguments' => array(
        'access content'
      ),
      'type' => MENU_CALLBACK,
      'file' => 'scratchpad.login.inc'
    ),
    'admin/reports/updates/check' => array(
      'title' => 'Manual update check',
      'page callback' => 'update_manual_status',
      'access arguments' => array(
        'administer site configuration'
      ),
      'file' => 'scratchpad.fetch.inc',
      'type' => MENU_CALLBACK
    ),
    'admin/reports/updates' => array(
      'title' => 'Available updates',
      'description' => 'Get a status report about available updates for your installed modules and themes.',
      'page callback' => 'update_status',
      'access arguments' => array(
        'administer site configuration'
      ),
      'file' => 'scratchpad.report.inc',
      'weight' => 10
    ),
    'admin/reports/updates/list' => array(
      'title' => 'List',
      'page callback' => 'update_status',
      'access arguments' => array(
        'administer site configuration'
      ),
      'file' => 'scratchpad.report.inc',
      'type' => MENU_DEFAULT_LOCAL_TASK
    ),
    'report_scratchpad' => array(
      'title' => '',
      'page callback' => 'scratchpad_report_site',
      'access arguments' => array(
        'access content'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_CALLBACK
    ),
    'scratchpads' => array(
      'title' => 'Scratchpad List',
      'page callback' => 'scratchpad_list_scratchpads',
      'access arguments' => array(
        'access content'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_CALLBACK
    ),
    'scratchpads/list' => array(
      'title' => 'Scratchpad List',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -10
    ),
    'scratchpads/serial' => array(
      'title' => 'Serial',
      'page callback' => 'scratchpad_list_scratchpads_serial',
      'access arguments' => array(
        'access content'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_CALLBACK
    ),
    'scratchpads/json' => array(
      'title' => 'Serial',
      'page callback' => 'scratchpad_list_scratchpads_serial',
      'page arguments' => array(
        TRUE
      ),
      'access arguments' => array(
        'access content'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_CALLBACK
    ),
    'scratchpads/thumbs' => array(
      'title' => 'Thumbnails',
      'page callback' => 'scratchpad_list_scratchpads_thumbs',
      'access arguments' => array(
        'access content'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_LOCAL_TASK
    ),
    'scratchpads/table' => array(
      'title' => 'Table',
      'page callback' => 'scratchpad_list_scratchpads_table',
      'access arguments' => array(
        'view scratchpad data'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_LOCAL_TASK
    ),
    'scratchpads/emails' => array(
      'title' => 'Scratchpad List',
      'page callback' => 'scratchpad_list_scratchpads_emails',
      'access arguments' => array(
        'view scratchpad data'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_LOCAL_TASK
    ),
    'scratchpads/stats' => array(
      'title' => 'Statistics',
      'page callback' => 'scratchpad_list_scratchpads_stats',
      'access arguments' => array(
        'access content'
      ),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_LOCAL_TASK
    )
  );
}

/**
 * Implementation of hook_theme
 */
function scratchpad_theme(){
  module_load_include('module', 'update');
  return update_theme();
}

/**
 * Implementation of hook_cron
 * 
 * Cron function reports this Scratchpad to central server(s).
 */
function scratchpad_cron(){
  module_load_include('cron.inc', 'scratchpad');
  _scratchpad_cron();
  // Cron should check for updates if there is no update data cached or if the
  // configured update interval has elapsed.
  module_load_include('module', 'update');
  if(!_update_cache_get('update_available_releases') || ((time() - variable_get('update_last_check', 0)) > 604800)){ // Seconds in a week
    update_refresh();
    // Perhaps notify scratchpad@nhm.ac.uk of update status here.
  }
}

/**
 * Implementation of hook_footer
 * 
 * Add the Google analytics code to the footer of the site.  This code helps to
 * define exactly what a Scratchpad is.
 */
function scratchpad_footer($main = 0){
  return '<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
_uacct = "UA-2428547-2";
urchinTracker();
</script>';
}
