<?php

/**
 * @file
 * 
 * This module defines whether or not a Drupal site is a Scratchpad.  By
 * enabling this module, you are consenting to the use of statistics from your
 * site being used by the Scratchpad team for promotion of the Scratchpads.
 * 
 * This module does the following:
 * 
 * - Reports back to home.scratchpads.eu statistics about this site.
 * - Adds the Scratchpad Google analytics code to the footer of your site.
 * - Adds a page to the site "/scratchpads" which lists all other Scratchpads.
 */

/**
 * Implementation of hook_menu
 */
function scratchpad_menu(){
  return array(
    'report_scratchpad/%' => array(
      'title' => '',
      'page callback' => 'scratchpad_report_site',
      'access arguments' => array('access content'),
      'page arguments' => array(1),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_CALLBACK
    ),
    'scratchpads' => array(
      'title' => 'Scratchpad List',
      'page callback' => 'scratchpad_list_scratchpads',
      'access arguments' => array('access content'),
      'file' => 'scratchpad.list.inc',
      'type' => MENU_CALLBACK
    )
  );
}

/**
 * Implementation of hook_cron
 * 
 * Cron function reports this Scratchpad to central server(s).
 */
function scratchpad_cron(){
  // Don't report if we're a "dev" or D6 upgrade site.
  if(substr($_SERVER['HTTP_HOST'],0,3)!='d6.' && substr($_SERVER['HTTP_HOST'],0,4)!='dev.'){
    // Once a week (this could be made more frequent) we'll report that we exist
    // to a central repository which can then build a list of all Scratchpads.
    if(variable_get('scratchpad_last_reported',0) < time()-604800){// 604800 = seconds in a week
      // Send the update to our central server
      $central_servers = variable_get('scratchpad_central_servers', array('http://home.scratchpads.eu/'));
      $nodes = db_fetch_array(db_query("SELECT COUNT(nid) AS nodes FROM node;"));
      $users = db_fetch_array(db_query("SELECT COUNT(uid) AS users FROM users"));
      $views = db_fetch_array(db_query("SELECT SUM(totalcount) AS totalcount FROM node_counter;"));
      $report_data = array(
        'site_url' => $_SERVER['HTTP_HOST'],
        'site_title' => variable_get('site_name','Scratchpad'),
        'site_mission' => variable_get('site_mission',''),
        'nodes' => $nodes['nodes'],
        'users' => $users['users'] - 2,
        'views' => $views['totalcount']
      );
      foreach($central_servers as $central_server){
        file_get_contents($central_server . 'report_scratchpad/' . urlencode(serialize($report_data))); // Could run into GET limits here. Ho hum!
      }
      variable_set('scratchpad_last_reported', time());
    }
    if(variable_get('scratchpad_last_updated',0) < time()-86400){// 86400 = seconds in a day
      // Also update the sites list for this site
      $central_servers = variable_get('scratchpad_central_servers', array('http://home.scratchpads.eu/report_scratchpad/'));
      $sites = array();
      foreach($central_servers as $central_server){
        $sites = array_merge($sites, unserialize(file_get_contents($central_server . 'scratchpads/serial')));     
      }
      variable_set('scratchpad_sites_list', $sites);
      variable_set('scratchpad_last_updated', time());
    }
  }
}

/**
 * Implementation of hook_footer
 * 
 * Add the Google analytics code to the footer of the site.  This code helps to
 * define exactly what a Scratchpad is.
 */
function scratchpad_footer($main = 0){
  return '<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
_uacct = "UA-2428547-2";
urchinTracker();
</script>';
}