<?php

function scratchpads_migrate_menu(){
  $items['admin/content/scratchpads-migrate'] = array(
    'title' => 'Scratchpads migrate',
    'description' => t('Scratchpad migration settings - please complete to get your site migrated.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'scratchpads_migrate_form'
    ),
    'access arguments' => array(
      'assign roles'
    )
  );
  return $items;
}

/**
 * Return the array defining the site type options
 * (Implemented as function rather than constant
 * for future compatibility as these may change
 * in sync with SP2 counterparts)
 */
function _scratchpads_migrate_site_type_options() {
  return array(
    'Research domain' => array(
      'biogeography' => t('Biogeography'),
      'taxonomy_systematics' => t('Taxonomy/Systematics'),
      'conservation' => t('Conservation'),
      'paleontology_fossils' => t('Paleontology/Fossils'),
      'mineralogy' => t('Mineralogy'),
      'other_research_domain' => t('Other')
    ),
    'Scope/Focus' => array(
      'society_organisation' => t('Society/Organisation'),
      'journal' => t('Journal'),
      'research_project_data' => t('Research project/data'),
      'citizen_science_project' => t('Citizen science project'),
      'other_scope_focus' => t('Other')
    ),
    'Taxonomic area' => array(
      'plants' => t('Plants'),
      'animals' => t('Animals'),
      'algae_fungi' => t('Algae-Fungi'),
      'other_taxonomic_area' => t('Other'),
      'no_taxonomic_restriction' => t('No taxonomic restriction'),
      'taxonomic_area_not_applicable' => t('Not applicable')
    ),
    'Ecoregion' => array(
      'marine' => t('Marine'),
      'freshwater' => t('Freshwater'),
      'terrestrial' => t('Terrestrial'),
      'no_ecoregional_restriction' => t('No ecoregional restriction'),
      'ecoregion_not_applicable' => t('Not applicable')
    ),
    'Geographical extent' => array(
      'global_no_geographic_restriction' => t('Global/No geographic restriction'),
      'continental_subcontinental' => t('Continental/subcontinental'),
      'regional' => t('Regional (More than one country in a region, eg. Baltic countries)'),
      'local' => t('Local (Country/sub-country level)'),
      'geographical_extent_not_applicable' => t('Not applicable')
    )
  );
}
function scratchpads_migrate_form(&$form_state){
  $form['biological_classifications'] = array(
    '#type' => 'fieldset',
    '#title' => t('Classifications'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Please select your biological classifications below.")
  );
  foreach(taxonomy_get_vocabularies() as $vocabulary){
    $form['biological_classifications'][$vocabulary->vid] = array(
      '#type' => 'select',
      '#title' => $vocabulary->name,
      '#options' => array(
        0 => t('Not a biological classification'),
        1 => 'Animal',
        2 => 'Plant/Fungi',
        3 => 'Moneran'
      ),
      '#default_value' => scratchpads_migrate_biological_classification_load($vocabulary->vid),
      '#parents' => array(
        'biological_classifications',
        $vocabulary->vid
      )
    );
  }
  $form['settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Scratchpads 2 has a completely redesigned home page. We <strong>highly recommend</strong> you use this, but if you really want to keep your old home page, check this box.")
  );
  $form['settings']['keep_homepage'] = array(
    '#type' => 'checkbox',
    '#title' => t('I want to keep my old home page.'),
    '#default_value' => variable_get('keep_homepage', false)
  );
  $form['settings']['site_type'] = array(
    '#type' => 'fieldset',
    '#title' => t('Type of site'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t('Please select one or more tags that describe your site.'),
  );
  $site_type_options = _scratchpads_migrate_site_type_options();
  $site_type_defaults = variable_get('site_type', array());
  foreach ($site_type_options as $site_type_category => $site_type_sub_options) {
    $site_type_category_machine = 'type_' . strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $site_type_category));
    $site_type_sub_defaults = array_intersect($site_type_defaults, array_keys($site_type_sub_options));
    $site_type_definition = array(
      '#type' => 'checkboxes',
      '#title' => t($site_type_category),
      '#required' => TRUE,
      '#multiple' => TRUE,
      '#default_value' => $site_type_sub_defaults,
      '#options' => $site_type_sub_options
    );
    $form['settings']['site_type'][$site_type_category_machine] = $site_type_definition;
  }
  $form['migrate_ready'] = array(
    '#type' => 'checkbox',
    '#title' => t('Migrate my site now'),
    '#description' => t("Is your site ready to be migrated? Check this box and click 'Save'")
  );
  if(variable_get('migrate_ready', false)){
    drupal_set_message('Your site has been queued for migration');
    $form['migrate_ready']['#default_value'] = 1;
    $form['migrate_ready']['#disabled'] = true;
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );
  return $form;
}

function scratchpads_migrate_form_submit($form, &$form_state){
  global $base_url;
  foreach($form_state['values']['biological_classifications'] as $vid => $classification_type){
    if($classification_type > 0){
      scratchpads_migrate_biological_classification_save($vid, $classification_type);
    }else{
      scratchpads_migrate_biological_classification_delete($vid);
    }
  }
  variable_set('keep_homepage', $form_state['values']['keep_homepage']);
  $site_type = array();
  $site_type_options = _scratchpads_migrate_site_type_options();
  foreach(array_keys($site_type_options) as $site_type_category) {
    $site_type_category_machine = 'type_' . strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $site_type_category));
    $site_type = array_merge($site_type, array_filter($form_state['values'][$site_type_category_machine]));
  }
  variable_set('site_type', $site_type);
  if($form_state['values']['migrate_ready']){
    variable_set('migrate_ready', true);
    $message = array(
      'to' => 'd.koureas@nhm.ac.uk',
      'subject' => t('Migrate !host', array(
        '!host' => parse_url($base_url, PHP_URL_HOST)
      )),
      'body' => t('!site !url is ready for migration', array(
        '!site' => variable_get('site_name', "Default site name"),
        '!url' => $base_url
      ))
    );
    drupal_mail_send($message);
  }else{
    drupal_set_message('Migration settings updated.');
  }
}

function scratchpads_migrate_biological_classification_load($vid){
  return db_result(db_query("SELECT type FROM {scratchpads_migrate_biological_classification} WHERE vid = %d", $vid));
}

function scratchpads_migrate_biological_classification_save($vid, $classification_type){
  $data = array(
    'vid' => $vid,
    'type' => $classification_type
  );
  drupal_write_record('scratchpads_migrate_biological_classification', $data);
}

function scratchpads_migrate_biological_classification_delete($vid){
  db_query('DELETE FROM {scratchpads_migrate_biological_classification} WHERE vid = %d', $vid);
}


