<?php



/**
 * Implementation of hook_menu().
 */
function printable_nhm_menu($may_cache) {

  if (!$may_cache) {
		
		$path = drupal_get_path('module', 'printable_nhm');
		drupal_add_css($path.'/printable_nhm.css', 'module', 'all', false);
		drupal_add_js($path.'/printable_nhm.js');	
		
  }

}


/**
 * Return a themed printable link.
 */
function phptemplate_printable_link($url) {
	
	if(user_access('print pages')){

	  $output = '<div class="nhm-printable">';
		$img = sprintf('<img src="/%s/extras/printer.png" width="16" height="16" alt="%s" /> %s', drupal_get_path('module', 'printable_nhm'), t('print this page'), t('print this page'));

	  $output .= l($img, 'printable/'. $url, array(), null, null, false, true);
	  $output .= '</div>';
	  return $output;

	}

}