<?php



/**
 * Implementation of hook_menu().
 */
function printable_nhm_menu() {

/* TODO
   Non menu code that was placed in hook_menu under the '!$may_cache' block
   so that it could be run during initialization, should now be moved to hook_init.
   Previously we called hook_init twice, once early in the bootstrap process, second
   just after the bootstrap has finished. The first instance is now called boot
   instead of init.
   
   In Drupal 6, there are now two hooks that can be used by modules to execute code
   at the beginning of a page request. hook_boot() replaces hook_boot() in Drupal 5
   and runs on each page request, even for cached pages. hook_boot() now only runs
   for non-cached pages and thus can be used for code that was previously placed in
   hook_menu() with $may_cache = FALSE:
   
   Dynamic menu items under a '!$may_cache' block can often be simplified
   to remove references to arg(n) and use of '%<function-name>' to check
   conditions. See http://drupal.org/node/103114.
   
   The title and description arguments should not have strings wrapped in t(),
   because translation of these happen in a later stage in the menu system.
*/
  if (!$may_cache) {
		
		$path = drupal_get_path('module', 'printable_nhm');
		drupal_add_css($path.'/printable_nhm.css', 'module', 'all', false);
		drupal_add_js($path.'/printable_nhm.js');	
		
  }

}


/**
 * Return a themed printable link.
 */
function phptemplate_printable_link($url) {
	
	if(user_access('print pages')){

	  $output = '<div class="nhm-printable">';
		$img = sprintf('<img src="/%s/extras/printer.png" width="16" height="16" alt="%s" /> %s', drupal_get_path('module', 'printable_nhm'), t('print this page'), t('print this page'));

	  $output .= l($img, 'printable/'. $url, array('query' => null, 'fragment' => null, 'absolute' => TRUE, 'html' => TRUE));
	  $output .= '</div>';
	  return $output;

	}

}