<?php
function ispecies_install(){
  drupal_install_schema('ispecies');  
}

function ispecies_uninstall(){
  drupal_uninstall_schema('ispecies');
}

function ispecies_schema(){
  $tables['ispecies'] = array(
    'fields' => array(
      'nid' => array('type' => 'int', 'not null' => true),
      'url' => array('type' => 'text'),
      'ispeciestype' => array('type' => 'varchar', 'length' => 128)
    ),
    'primary key' => array('nid'));
  return $tables;
}