<?php

/**
 * @file
 * 
 * Provides the views which can be added as blocks to any page.
 * 
 * Inorder to make it easier to additional iSpecies blocks, we'll implement our
 * own hook hook_ispecies.  This hook should return an array which gives info
 * on how a block can be build (callback, arguments, etc).
 * 
 * hook_ispecies();
 */

/**
 * Implementation of hook_node_info
 */
function ispecies_node_info() {  
  return array (
    'ispecies' => array (
      'name' => t('iSpecies Cache'), 
      'module' => 'ispecies', 
      'description' => t('Cached iSpecies content.'), 
      'locked' => true
    )
  );
}

function ispecies_menu(){
  $items = array();
  $items['ispecies'] = array(
    'page callback' => 'ispecies_ajax_callback', 
    'access arguments' => array (
      'access content' ), 
    'type' => MENU_CALLBACK );
  return $items;
}

function ispecies_ajax_callback($module, $tid = false){
  if(!$tid){
    // If tid is not set, get the referer and use the final part of that as the
    // tid
    $tid = array_pop(explode("/",referer_uri()));
  }
  if (! $tid) {
    // Get the referer and use the final part of that as the tid
    $tid = array_pop ( explode ( "/", referer_uri () ) );
  }
  print json_encode(ispecies_get_data($module, $tid));
  exit;
}

function ispecies_get_data($module, $tid){
  $term = taxonomy_get_term ( $tid );
  $term_name = $term->name;
  $ispecies_views = module_invoke_all('ispecies');  
  $sort_orders = variable_get('view_sort-limits', array());
  if (isset($sort_orders[$module]) && arg(0)!='views-sort'){
    if(function_exists($ispecies_views[$module]['callback'])){
      return call_user_func($ispecies_views[$module]['callback'], $term_name, $sort_orders[$module]);
    } else {
      watchdog("ispecies", "Function doesn't exist: " . $ispecies_views[$module]['callback']);
    }
  } else {
    if(function_exists($ispecies_views[$module]['callback'])){
      return call_user_func($ispecies_views[$module]['callback'], $term_name);
    } else {
      watchdog("ispecies", "Function doesn't exist: " . $ispecies_views[$module]['callback']);
    }
  }
}

/**
 * Implementation of hook_init
 */
function ispecies_init(){
  if(is_numeric(arg(2)) && arg(0)=='taxonomy' && arg(1)=='term'){
    ispecies_add_js(arg(2));
  }
}

function ispecies_add_js($tid){
  drupal_add_js(drupal_get_path('module','ispecies').'/ispecies.js');
  drupal_add_js(drupal_get_path('module','citation')."/citation.js");
  drupal_add_js('page_tid = '.$tid.';' , 'inline');
}
/**
 * Implementation of hook_viewsapi
 */
function ispecies_views_api(){
  return array('api' => 2);
}