<?php
/**
 * This file helps with the install of the autotag module.  All it does is sets the highest node ID for 
 * nodes which cron will search.  Cron eventually becomes unnecessary for this module.
 */
/**
 * Implementation of hook_install
 */
function tree_install(){
  // Create tables.
  drupal_install_schema('tree');
}

function tree_uninstall(){
  // Remove tables.
  drupal_uninstall_schema('tree');

}