<?php

/**
 * Implementation of hook_menu
 */
function classification_import_menu(){
  return array(
    'admin/content/taxonomy/import' => array(
      'title' => 'Import',
      'description' => 'Import terms and metadata into a taxonomy',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('classification_import_form'),
      'access arguments' => array('administer taxonomy'),
      'file' => 'classification_import.form.inc',
      'type' => MENU_LOCAL_TASK
    )
  );
}

/**
 * Implementation of hook_help
 */
function classification_import_help($path, $arg){
  if($path == 'admin/content/taxonomy/import'){
    if($arg[4]){
      // We're importing in to a vocab, give help
      $additional_help = module_invoke_all('classification_import_help');
      if($additional_help){
        if(!is_array($additional_help)){
          $additional_help = array($additional_help);
        }
        $additional_help = '<ul><li>' . implode("</li><li>", $additional_help) . '</li></ul>';
      } else {
        $additional_help = '';
      }
      return '<p>' . t('There are a number of different options open to you for importing your taxonomy.  Additional import functions can also be installed.') . '</p>' . $additional_help;
    } else {
      // We're viewing the select a vocab page, advise to select a vocab.
      $vocabs = taxonomy_get_vocabularies();
      $list_items = array();
      foreach($vocabs as $vid => $vocab){
        // FIXME - We're here, listing the vocabs for the overview page.
        // $list_items
        $list_items[] = l(check_plain($vocab->name),'admin/content/taxonomy/import/'.$vid);
      }
      return theme('item_list', $list_items, t('Click on the vocabulary into which you would like to import terms'));
    }
  }
}

/**
 * Classification load terms
 * 
 * This function is called by the batch api of the contrib modules.
 */
function classification_import_load_terms($vid){
  // First we'll get the root term id so that we know where to start from
  $parent_id = db_result(db_query("SELECT parent FROM {classification_import_temp} WHERE parent NOT IN (SELECT id FROM classification_import_temp)"));
  classification_import_load_terms_recurse($parent_id, $vid);
  // Finally clear the table.
  db_query("TRUNCATE {classification_import_temp}");
}

function classification_import_load_terms_recurse($parent_id, $vid, $parent=0){
  $results = db_query("SELECT id, data FROM {classification_import_temp} WHERE parent = '%s'", $parent_id);
  while($row = db_fetch_array($results)){
    $data = unserialize($row['data']);
    foreach($data as $key => $value){
      if(is_array($value)){
        $data[$key] = $value[0];
      }
      // FIXME Hacky work around for the term_node module - this belongs in the
      // term_node module itself.
      $data['field_'.$key] = array(array('value' => $data[$key])); 
    }
    $data['vid'] = $vid;
    $data['parent'] = $parent;
    taxonomy_save_term($data);
    classification_import_load_terms_recurse($row['id'], $vid, $data['tid']);
  }
}


/**
 * 
 */
function classification_import_batch_import_finished($success, $results, $operations) {
  variable_del('eol_import_doing_import');
  if ($success) {
    drupal_set_message(t('The import has been performed.'));
  }
  else {
    drupal_set_message(t('An error occurred and processing did not complete.'), 'error');
  }
}