<?php

/**
 * An attempt at creating a module for inputting specimens into Drupal
 * 
 * This module uses the Darwin Core Schema (DwC 1.21
 */

/**
 * Implementation of hook_menu()
 */
function bio_image_menu($maycache){
  $items = array();
  if (!$may_cache) {// FIXME - This may be cached once developed
    $items[] = array(
    'path' => 'bio_image/autocomplete',
    'title' => t('Autocomplete bio_image thingumy'),
    'callback' => 'bio_image_autocomplete',
    'access' => user_access('create page'),
    'type' => MENU_CALLBACK
    );
  }
  return $items;
}

/**
 * Function for the autocomplete
 */
function bio_image_autocomplete($field, $string=''){
  switch ($field){
    case 'taxonomicname':
      $results = db_query_range("SELECT DISTINCT name AS string FROM {term_data} WHERE LOWER(name) LIKE LOWER('%s%%');", $string, 0, 10);
      break;
    default:
      $results = db_query_range("SELECT DISTINCT %s AS string FROM {bio_image} WHERE LOWER(%s) LIKE LOWER('%s%%')", $field, $field, $string, 0, 10);
  }
  while ($result = db_fetch_object($results)){
    $matches[$result->string] = check_plain($result->string);
  }
  print drupal_to_js($matches);
  exit();
}

function bio_image_validate($form_id,&$form_values){
  /*
  $form_values['bio_image_specimen_group'] = $form_values['taxonomy']['bio_image_specimen_group'];
  $form_values['bio_image_biblio_group'] = $form_values['taxonomy']['bio_image_biblio_group'];
  $form_values['title'] = $form_values['taxonomy']['title'];
  $form_values['body_filter'] = $form_values['taxonomy']['body_filter'];
  unset($form_values['taxonomy']['bio_image_specimen_group']);
  unset($form_values['taxonomy']['bio_image_biblio_group']);
  unset($form_values['taxonomy']['title']);
  unset($form_values['taxonomy']['body_filter']);
  */
}

/**
 * Implementation of hook_form_alter()
 */
function bio_image_form_alter($form_id, &$form){
  if($form_id != 'image_node_form'){
    return;
  }
  drupal_add_js('$("span.addnode_form").each(function(){alert($(this).hide());});','module','footer');
  
  $form['taxonomy']['#title'] = t('Annotations');
  $form['taxonomy']['#collapsible'] = false;
  $form['body_filter']['body']['#title'] = t('Notes');
  //$form['taxonomy']['body_filter'] = $form['body_filter'];
  //$form['taxonomy']['title'] = $form['title'];
  //$form['taxonomy']['bio_image_specimen_group'] = $form['bio_image_specimen_group'];
  //$form['taxonomy']['bio_image_biblio_group'] = $form['bio_image_biblio_group'];
  //unset($form['title']);
  //unset($form['body_filter']);
  //unset($form['bio_image_biblio_group']);
  //unset($form['bio_image_specimen_group']);
  $form['attachments']['#type'] = 'hidden';
  $form = subform_element_separate_data_prepare($form);
  //$form['#validate'] = (isset($form['#validate']))? array_merge($form['#validate'],array('bio_image_validate'=>array())) : array('bio_image_validate'=>array());
  //print_r($form);exit;
}