<?php

/**
 * An attempt at creating a module for inputting specimens into Drupal
 * 
 * This module uses the Darwin Core Schema (DwC 1.21
 */

/**
 * Implementation of hook_viewsapi
 */
function bio_image_views_api(){
  return array('api' => 2);
}

/**
 * Implementation of hook_form_alter()
 */
function bio_image_form_alter($form, $form_state, &$form_id){
  if($form_id == 'image_node_form'){    
    $form['taxonomy']['#title'] = t('Annotations');
    $form['body_field']['body']['#title'] = t('Notes');
    $form['#after_build'] = array('bio_image_node_form_pre_render');
    //var_export(content_fields('image_specimen','image'));exit;
  }
  // Don't allow editing of darwincore vocabularies
  elseif ($form_id == 'taxonomy_form_vocabulary'){
    if($form['module']['#value'] == 'bio_image'){
      $vocabulary = check_plain($form['identification']['name']['#default_value']);
      drupal_set_message(t('The %vocabulary vocabulary can not be edited', array('%vocabulary'=>$vocabulary)), 'error');
      drupal_goto('admin/content/taxonomy');
    }
  }
  elseif ($form_id == 'taxonomy_overview_vocabularies'){
    foreach($form as $key => $value){
      if(is_numeric($key) && isset($value['#vocabulary']['module']) && $value['#vocabulary']['module'] == 'bio_image'){
        unset($form[$key]);
      }
    }
  }
}

function bio_image_node_form_pre_render($form, &$form_state){
  $form['taxonomy']['image_publication'] = $form['image_publication'];
  unset($form['image_publication']);
  $form['taxonomy']['image_specimen'] = $form['image_specimen'];
  unset($form['image_specimen']);
  return $form;
}