<?php

/**
 * Implementation of hook_theme_registry_alter
 */
function femail_theme_registry_alter(&$theme_registry){
  $theme_registry['forums']['template'] = drupal_get_path('module','femail').'/forums';
  $theme_registry['forums']['theme path'] = drupal_get_path('module','femail');
  $theme_registry['forums']['theme paths'] = array(drupal_get_path('module','femail'));
  $theme_registry['forums']['preprocess functions'] = array_merge($theme_registry['forums']['preprocess functions'], array('template_preprocess_femail_forums'));
}

/**
 * Defined above in hook_theme_registry_alter
 */
function template_preprocess_femail_forums(&$variables){
  if($variables['tid']){
    // We're viewing a Forum, or a Container, lets check this isn't a container
    if(!in_array($variables['tid'], variable_get('forum_containers'))){
      // We're viewing a forum
      $variables['show_femail_link'] = $variables['tid'];
    }
  }
}

/**
 * Implementation of hook_theme
 */
function femail_theme($existing, $type, $theme, $path) {
  return array(
    'femail_link' => array(
      'arguments' => array('tid' => NULL),
      'file' => 'femail.theme-functions.php'
    )
  );
}

/**
 * Implementation of hook_taxonomy
 */
function femail_taxonomy($op, $type, $array = NULL){
  if($type == 'term'){
    $emails = variable_get('femail_emails', array());
    if($op == 'delete'){
      unset($emails[$array['tid']]);
      variable_set('femail_emails', $emails);      
    } else {
      // Check if this is a term from the forum vocab
      if($array['vid'] == variable_get('forum_nav_vocabulary', 0)){
        $emails = variable_get('femail_emails', array());
        unset($emails[$array['tid']]);
        global $base_url;
        $parts = parse_url($base_url);
        $email = preg_replace("/[^0-9a-z\-]/","",strtolower(str_replace(" ", "-", $array['name'])));
        if(array_search($email . '@' . $parts['host'], $emails)){
          $i = 2;
          while(array_search($email."_".$i.'@'.$parts['host'], $emails)){
            $i++;
          }
          $email = $email."_".$i;
        }
        $emails[$array['tid']] = $email . '@' . $parts['host'];
        variable_set('femail_emails', $emails);      
      }      
    }
  }
}