#!/bin/bash
while read line
do
	MESSAGE=${MESSAGE}"\n"$line
done
DOMAIN=`echo -e $MESSAGE | grep ^To | head -n1 | sed "s/.*@//"`
echo -e $MESSAGE | /var/www/simon.rycroft.name/scratchpad/drush/drush -r /var/www/simon.rycroft.name/scratchpad -l http://$DOMAIN femail
