<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function printable_help($section) {
  if(substr($section,0,14)=='taxonomy/term/'){
    static $output = FALSE;
    if ($output === FALSE) {
      $output = TRUE;
      return theme('printable_link', $_GET['q']);
    }
  }
}

/**
 * Implementation of hook_menu().
 */
function printable_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'printable',
      'title' => t('Print'),
      'access' => user_access('print pages'),
      'callback' => 'printable_page',
      'type' => MENU_CALLBACK
    );
  }
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function printable_perm() {
  return array('print pages');
}

/**
 * Menu callback; output a printable page.
 */
function printable_page() {
  $result = module_invoke('pagearray', 'page', substr($_GET['q'], 10));
  if ($result['status'] === FALSE) {
    switch ($result['value']) {
      case MENU_NOT_FOUND:
      case NULL:
        drupal_not_found();
        break;
      case MENU_ACCESS_DENIED:
        drupal_access_denied();
        break;
      case MENU_SITE_OFFLINE:
        drupal_site_offline();
        break;
    }
  }
  else {
    print theme('printable', $result['page']);
  }
}

/**
 * Return a themed printable link.
 */
function theme_printable_link($url) {
  $output = '<span class="printable">';
  $output .= l(t('printable page'), 'printable/'. $url);
  $output .= '</span>';
  return $output;
}

/**
 * Return the themed output of a printable page.
 */
function theme_printable($page) {
  // Adapted from _phptemplate_render();
  extract($page, EXTR_SKIP);       // Extract the variables to a local namespace.
  ob_start();                      // Start output buffering.
  include drupal_get_path('module', 'printable') .'/printable.tpl.php'; // Include the file.
  $contents = ob_get_contents();   // Get the contents of the buffer.
  ob_end_clean();                  // End buffering and discard.
  return $contents;                // Return the contents.
}