<?php
/**
 * implementation of hook_ispecies
 */
function nbnmap_ispecies(){
  return array (
    'nbnmap' => array (
      'title' => t ( 'National Biodiversity Network' ), 
      'description' => t ( 'Some info about NBN' ),
      'single' => TRUE,
      'callback' => 'nbnmap_ajax_callback' ) );
}

function nbnmap_ajax_callback($term_name, $limit = 20){
  $items = array ();  
  $name_client = new SoapClient('http://www.nbnws.net/ws/taxonomy/WSDL');
  $name_result = $name_client->GetTaxonomySearch(array("SpeciesName"=>$term_name));
  $taxonVersionKey = $name_result->Taxon->taxonVersionKey;

  $nbn_client = new SoapClient("http://www.nbnws.net/ws_3_3/ws/WSDL");
  $nbn_result = $nbn_client->GetGridMap(array("TaxonVersionKey"=>$taxonVersionKey));
  $map_url = $nbn_result->Map->Url;

  if ($map_url) {     
    $item = array(
      'body' => '<p style="text-align:center"><img id="nbn-map" src="'.$map_url.'" alt="'.$term_name.'" /></p>',
      'page_url' => 'http://data.nbn.org.uk/searchengine/search.jsp?tab=1&pg=1&searchTerm='.$term_name
    );    
    $items[] = $item;
    $urls = array($item['page_url']);
  }
  $urls = array('name' => 'NBN', 'url' => 'http://www.nbn.org.uk/', 'urls'=> $urls);
  $items['urls'] = $urls;
  $items['citation'] = theme('citation_url', $urls);
  return $items;
}
