<?php

/**
 * Implementation of hook_form_alter
 * 
 * Following alters the install form, skipping it alltogether so that the sites
 * are installed automatically, with no user input.
 */

function scratchpad_training_form_alter(&$form, $form_state, $form_id){
  if($form_id == 'install_configure_form'){
    $form_state = array (
      'storage' => NULL, 
      'submitted' => TRUE, 
      'values' => array (
        'site_name' => 'Scratchpad Training', 
        'site_mail' => 'scratchpad@nhm.ac.uk', 
        'account' => array(
          'name' => 'username',
          'mail' => 'scratchpad@nhm.ac.uk', 
          'pass' => 'password'), 
        'date_default_timezone' => '3600', 
        'clean_url' => '1',
        'update_status_module' => array (1 => 1), 
        'op' => 'Save and continue', 
        'submit' => 'Save and continue', 
        'form_id' => 'install_configure_form'));
    scratchpadify_install_configure_form_submit($form, $form_state);
  }
}