<?php
// $Id$

function fotonotes_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':    
    case 'pgsql':
      db_query("CREATE TABLE {fotonotes} (
			  `nid` int(10) unsigned NOT NULL default '0',
			  `uid` int(10) unsigned NOT NULL default '0',
			  `annotation_id` varchar(255) default '0',
			  `title` varchar(255) default '0',
			  `content` text,
			  `xml` text
			) /*!40100 DEFAULT CHARACTER SET UTF8 */ ");
      break;
  }
}