<?php

/**
 * Implementation of hook_install
 */
function tcs_import_install(){
  // We're just going to add additional fields to the classification_import_temp
  // table.
  db_add_field($ret, 'classification_import_temp', 'ref', array('type' => 'text'));
  db_add_field($ret, 'classification_import_temp', 'url', array('type' => 'text'));
}

/**
 * hook_uninstall
 */
function tcs_import_uninstall(){
  // FIXME - Remove the ref column that we added.
}