<?php
function node_term_edit_form_alter(&$form, &$form_state, $form_id){
  // Return if this isn't a node form  
  if($form['#id'] != 'node-form'){return;}  
  // Check that the tid is set and is numeric
  if(isset($_GET['tid']) && is_numeric($_GET['tid'])){
    // Add it to the form
    $term = taxonomy_get_term($_GET['tid']);
    if($term){
      $form['#node']->taxonomy[$_GET['tid']] = $term;
      $form['#redirect'] = 'taxonomy/term/'.$_GET['tid'];
      if(count($form_state['storage']) && !$form_state['submitted']){
        drupal_set_message(t('The term "@term" will be automatically added to this node.', array('@term' => $term->name)));
      }
    }
  }
}