<?php
/**
 * Add the javascript file
 */
function tablesorter_views_pre_render(&$view){
  // Lets check to see if this view is a table view
  foreach($view->display as $view_display){
    if($view_display->display_options['style_plugin'] == 'table'){
    	drupal_add_js (drupal_get_path('module', 'tablesorter') . '/tablesorter.js');
    	drupal_add_css(drupal_get_path('module', 'tablesorter') . '/tablesorter.css');
    }
  }
}

/**
 * Implementation of hook_viewsapi
 */
function tablesorter_viewsapi(){
  return array('api' => 2);
}