<?php

/** 
* Implementation of hook_init().
* Define a callback path
*/
function taxonomy_tree_init(){
  
  drupal_add_js(array('taxonomyTreeCallbackPath' => url('taxonomy_tree/callback')), 'setting');
	
}

/** 
*Implementation of hook_perm(). 
*/
function taxonomy_tree_perm(){

  return array('administer taxonomy tree');

}

/** 
*Implementation of hook_menu(). 
*/
function taxonomy_tree_menu(){
  
  $items['admin/settings/taxonomy_tree'] = array(
    'title' => 'Taxonomy tree',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('taxonomy_tree_admin_settings_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer taxonomy tree'),
    'file' => 'taxonomy_tree.admin.inc',
  );
  
  $items['taxonomy_tree/callback'] = array(
    'title' => 'Add project',
    'page callback' => 'taxonomy_tree_callback',
    'access arguments' => array('administer taxonomy tree'),
    'type' => MENU_CALLBACK,
    'file' => 'taxonomy_tree.callbacks.inc',
  );

  return $items;
  
}


function taxonomy_tree_add_files(){
   
     $path = drupal_get_path('module', 'taxonomy_tree');

     drupal_add_js($path.'/js/plugins/jquery.cookie.js');
     drupal_add_js($path.'/js/plugins/jquery.treeview.js');
     drupal_add_js($path.'/js/plugins/jquery.treeview.async.js');
     drupal_add_js($path.'/js/taxonomy_tree.js');
     drupal_add_css($path.'/css/taxonomy_tree.css');
        
}


/** 
*Implementation of hook_alter(). 
*/
function taxonomy_tree_form_alter(&$form, $form_state, $form_id) {
  
  if (isset($form['type']) && isset($form['#node'])) {

    if(count($form['taxonomy'])){
      
    $vocabularies = taxonomy_get_vocabularies($form['#node']->type);
    
      foreach($vocabularies as $vid => $vocabulary){
 
        $taxonomy_tree_node_types = variable_get('taxonomy_tree_'.$vid, array());
      
        if($taxonomy_tree_node_types[$form['type']['#value']]){
      
        $form['taxonomy'][$vid]['#process'] = array('taxonomy_tree_process_field');

        $form['taxonomy_tree'][$vid] = array('#type' => 'hidden', '#value' => $vid, '#parents' => array('taxonomy_tree', $vid));

        }
      
      }
      
    if(count($form['taxonomy_tree'])){
      
      $form['#submit'] = array('taxonomy_tree_node_form_submit') + $form['#submit'];
      
    }  
    
    }

  
  }

  
}


function taxonomy_tree_node_form_submit($form, &$form_state) {
 
 $taxa_vid = $form_state['values']['taxa_vid'];
 
 foreach($form_state['values']['taxonomy_tree'] as $vid){
   
   if(count($form_state['values']['taxonomy'][$vid])){
     
     foreach($form_state['values']['taxonomy'][$vid] as $tid){

       if(!$form['#post']['expanded'][$tid]){
       // This term has not been expanded, so we need to see if it has any children to automatically select
       
       taxonomy_tree_select_children($form_state, $vid, $tid);
       
       }
       
     }
     
   }
   
 }


}

/** 
* Select all children of a term;
* Recursive;
*/
function taxonomy_tree_select_children(&$form_state, $vid, $tid){
  
  $children = taxonomy_get_children($tid);

  if(count($children)){

    foreach($children as $child){

      $form_state['values']['taxonomy'][$vid][$child->tid] = $child->tid;
      
      taxonomy_tree_select_children($form_state, $vid, $child->tid);

    }

  }

  
  
}


/** 
* Process the field
*/
function taxonomy_tree_process_field($element){
  
  $element['#type'] = 'markup';
  $element['#theme'] = 'taxonomy_tree_element';
  
  // Remove options as otherwise illegal choise will be detected
  unset($element['#options']);
  
  return $element;
  
  
}


/** 
* Implementation of hook_theme(). 
*/ 
function taxonomy_tree_theme() { 
  
  return array(
    
    'taxonomy_tree_element' => array(
      'arguments' => array('element' => NULL)
    ),
    
  );

}


/** 
* Theme the tree form element
*/
function theme_taxonomy_tree_element($element){

  taxonomy_tree_add_files();
  
  $vid = $element['#array_parents'][1];

  foreach($element['#value'] as $value){
    
    $selected .= '&tids['.$value.']='.$value;
    
  }
  
  drupal_add_js('$(document).ready(function() {TREE = new treeview(); TREE.init("'.$element['#id'].'","'.$vid.'","'.$selected.'")})', 'inline');
  
  $output = '<div '.drupal_attributes($element['#attributes']).'>';
  $output .= '<label>Terms for '.$element['#title'].'</label>';
  $output .= '<ul id="'.$element['#id'].'"></ul>';
  $output .= '</div>';
  
  return $output;
  
}





