<?php

/**
 * hook_block
 */
function remote_issue_tab_block($op = 'list', $delta = 0, $edit = array()){
  switch($op){
    case 'list':
      return array(
        array(
          'info' => t('Remote Issue Block'),
          'weight' => 1000,
          'status' => 1,
          'region' => 'left',
          'cache' => BLOCK_CACHE_PER_USER
        )
      );
      return $blocks;
    case 'configure':
      $feeds = array(
        t('-- Not Set --')
      );
      $results = db_query('SELECT fid, title, url FROM {aggregator_feed}');
      while($row = db_fetch_array($results)){
        $feeds[$row['fid']] = $row['title'] . ' (' . $row['url'] . ')';
      }
      return array(
        'remote_issue_tab_feed' => array(
          '#title' => t('Please select the feed to be used by the Remote Issue Block'),
          '#type' => 'select',
          '#options' => $feeds,
          '#default_value' => variable_get('remote_issue_tab_feed', 0),
          '#description' => t('Select the RSS Feed (A new RSS feed can be added using the <a href="!agg_url">Aggregator interface</a>, after which you will be redirected here.)', array(
            '!agg_url' => url('admin/content/aggregator/add/feed', array(
              'query' => array(
                'destination' => 'admin/build/block/configure/remote_issue_tab/0'
              )
            ))
          ))
        ),
        'remote_issue_tab_tab_title' => array(
          '#title' => t('Tab title'),
          '#type' => 'textfield',
          '#default_value' => variable_get('remote_issue_tab_tab_title', '')
        ),
        'uwho_client_key' => array(
          '#title' => t('UWho Client Key'),
          '#description' => t('Enter the key from the site you\'d like to enable your users to login to.'),
          '#type' => 'textfield',
          '#default_value' => variable_get('remote_issue_tab_uwho_key', '')
        ),
        'uwho_client_url' => array(
          '#title' => t('UWho Client URL'),
          '#description' => t('Enter the URL of the site you\'d like to enable your users to login to.  This must be EXACTLY as provided by the other site.'),
          '#type' => 'textfield',
          '#default_value' => variable_get('remote_issue_tab_uwho_url', '')
        ),
        'uwho_client_redirect_path' => array(
          '#title' => t('UWho Redirect PATH'),
          '#description' => t('Enter the path of the page on the remote site that you\'d like users to be redirected to (leave blank to use the default)'),
          '#type' => 'textfield',
          '#default_value' => variable_get('remote_issue_tab_redirect_path', '')
        ),
        'remote_issue_tab_footer' => array(
          '#title' => t('Footer'),
          '#type' => 'textarea',
          '#default_value' => variable_get('remote_issue_tab_footer', ''),
          '#description' => t('Enter text to be displayed below the Recent Issues.')
        )
      );
    case 'save':
      variable_set('remote_issue_tab_feed', $edit['remote_issue_tab_feed']);
      variable_set('remote_issue_tab_uwho_url', $edit['uwho_client_url']);
      variable_set('remote_issue_tab_uwho_key', $edit['uwho_client_key']);
      variable_set('remote_issue_tab_redirect_path', $edit['uwho_client_redirect_path']);
      variable_set('remote_issue_tab_footer', $edit['remote_issue_tab_footer']);
      if($edit['remote_issue_tab_tab_title'] == ''){
        variable_del('remote_issue_tab_tab_title');
      }else{
        variable_set('remote_issue_tab_tab_title', $edit['remote_issue_tab_tab_title']);
      }
      return;
    case 'view':
      global $user;
      if($user->uid){
        drupal_add_css(drupal_get_path('module', 'remote_issue_tab') . '/remote_issue_tab.css');
        drupal_add_js(drupal_get_path('module', 'remote_issue_tab') . '/remote_issue_tab.js');
        return array(
          'subject' => t('Remote Issue Block'),
          'content' => remote_issue_tab_content()
        );
      }
  }
}

/**
 * hook_footer
 */
function remote_issue_tab_footer($main = 0){
  return remote_issue_tab_content();
}

/**
 * hook_theme
 */
function remote_issue_tab_theme($existing, $type, $theme, $path){
  return array(
    'remote_issue_tab_feed_items' => array(
      'arguments' => array(
        'items' => NULL
      )
    ),
    'remote_issue_tab_feed_item' => array(
      'arguments' => array(
        'item' => NULL
      )
    )
  );
}

/**
 * helper for hook_block
 */
function remote_issue_tab_content(){
  $fid = (integer)variable_get('remote_issue_tab_feed', 0);
  if($fid && is_integer($fid)){
    // Load the required file
    module_load_include('pages.inc', 'aggregator');
    // This defaults to 20, which is more than enough for us!
    // Note, including fid in the SQL should be safe here, as we've ensured that
    // fid is an integer above.
    $items = aggregator_feed_items_load('SELECT * FROM {aggregator_item} WHERE fid = ' . $fid . ' ORDER BY timestamp DESC, iid DESC', $fid);
    $key = variable_get('remote_issue_tab_uwho_key', FALSE);
    $url = variable_get('remote_issue_tab_uwho_url', FALSE);
    $content = '<div id="open-close"><p>' . variable_get('remote_issue_tab_tab_title', t('Issues') . '...') . '</p></div>';
    if($key && $url){
      $content .= '<div class="subcontent"><div class="new-items">
  ' . uwho_client_block_content($key, $url, variable_get('remote_issue_tab_redirect_path', FALSE), t('Post New Issue')) . '
</div>';
    }
    return $content . theme('remote_issue_tab_feed_items', $items) . '<div class="footer">'.variable_get('remote_issue_tab_footer', '').'</div></div>';
  }else{
    return '';
  }
}

/**
 * theme function for items
 */
function theme_remote_issue_tab_feed_items($items = NULL){
  // We only want 10 items, so we'll count
  $content = '';
  if(count($items)){
    $item_count = 0;
    $content = '<div class="items"><h1>Recent Issues:</h1><ul>';
    foreach($items as $item){
      if($item_count == 10){
        break;
      }
      $content .= theme('remote_issue_tab_feed_item', $item, $item_count);
      $item_count++;
    }
    $content .= '</ul></div>';
  }
  return $content;
}

/**
 * theme function for items
 */
function theme_remote_issue_tab_feed_item($item = NULL, $item_count){
  return '<li class="' . ($item_count % 2 ? 'odd' : 'even') . ($item_count ? '' : ' first') . '"><div><h3><a href="' . $item->link . '" target="_blank">' . $item->title . '</a></h3><p>' . $item->description . '</p></div></li>';
}
