#!/bin/bash

# Create an X Virtual Frame Buffer (wait for it to start)
Xvfb :2 -screen 0 1040x768x24 -fbdir /tmp -nolisten inet6 &

# Make sure it has started and is sorted
sleep 60

# Make sure we're in the right folder
cd /var/www/html/screenshots

# For each site.
for i in $( ls -1 /var/www/html/sites |grep -v ^all$|grep -v ^default|grep -v \~|grep -v settings);do
	./firefox-screenshot $i
	# Pause between to not overload the server
	sleep 25
done

# Finally, kill the XVFB
killall Xvfb
