#!/bin/bash
# Change to the directory with the firefox-screen script and for output
cd /var/www/html/screenshots
# For each site.
for i in $( ls -1 /var/www/html/sites |grep -v ^all$|grep -v ^default|grep -v \~|grep -v settings);do
	echo $i
	convert $i.annotated.jpg -resize 280x210 $i.medium.annotated.jpg
	convert $i.annotated.jpg -resize 200x150 $i.small.annotated.jpg
	convert $i.jpg -resize 280x210 $i.medium.jpg
	convert $i.jpg -resize 200x150 $i.small.jpg
	convert -page +4+4 $i.280x210.jpg -matte \( +clone -background black -shadow 60x4+4+4 \) +swap -background none -mosaic -depth 8 -quality 95 $i.medium.drop.png
	convert -page +4+4 $i.280x210.annotated.jpg -matte \( +clone -background black -shadow 60x4+4+4 \) +swap -background none -mosaic -depth 8 -quality 95 $i.medium.drop.annotated.png
	# convert $i.160x120.jpg -bordercolor white -border 6 -bordercolor grey60 -border 1 -background none -rotate `perl -e 'print rand() * 30 - 15'` -background black \( +clone -shadow 60x4+4+4 \) +swap -background none -flatten -depth 8 -quality 95 $i.200x150-drop.jpg
	# convert -caption 'http://'$i'' $i.200x150.jpg -font Arial -gravity center -bordercolor Lavender -background black -polaroid -0 $i.polaroid.jpg
	# convert $i.160x120.jpg -bordercolor white  -border 6 -bordercolor grey60 -border 1 -bordercolor none  -background  none \( -clone 0  -rotate `perl -e 'print rand() * 30 - 15'` \) \( -clone 0  -rotate `perl -e 'print rand() * 30 - 15'` \) \( -clone 0  -rotate `perl -e 'print rand() * 30 - 15'` \) \( -clone 0  -rotate `perl -e 'print rand() * 30 - 15'` \) -delete 0  -border 100x80  -gravity center -crop 200x160+0+0  +repage  -flatten  -trim +repage -background black \( +clone -shadow 60x4+4+4 \) +swap -background none  -flatten -depth 8  -quality 95   $i.200x150-drop.jpg
done
