<?php
/**
 * hook_taxonomy
 */
function lowername_taxonomy($op, $type, $array = NULL){
  if($type == 'term'){
    switch($op){
      case 'insert':
        db_query("INSERT INTO {term_lowername} (tid, lowername) VALUES (%d, LOWER('%s'))", $array['tid'], $array['name']);
        break;
      case 'update':
        db_query("UPDATE {term_lowername} SET lowername = LOWER('%s') WHERE tid = %d", $array['name'], $array['tid']);
        if(!db_affected_rows()){ 
          // Just in case there wasn't already an entry in the database
          @db_query("INSERT INTO {term_lowername} (tid, lowername) VALUES (%d, LOWER('%s'))", $array['tid'], $array['name']);        
        }
        break;
      case 'delete':
        db_query("DELETE FROM {term_lowername} WHERE tid = %d", $array['tid']);
        break;
    }
  }
}

/**
 * FFS, I'm having to fix issues with other modules (NOT BLOODY MINE), here,
 * AAAAAAAAAAAAAAAAAAAAAAAAARGH!
 * 
 * This function shouldn't be needed, but in case other modules are naughty, and
 * add terms directly to the term_data table, then it is needed.
 * 
 * Also having to fix the classification module - this can be removed once we
 * get rid of the current classification editor. FIXME
 */
function lowername_cron(){
  db_query("DELETE FROM {term_lowername} WHERE lowername = 'taxon'");
  db_query("INSERT INTO {term_lowername} (tid,lowername) SELECT tid, LOWER(name) FROM term_data WHERE tid NOT IN (SELECT tid FROM term_lowername)");
}