<?php

/**
 * hook_menu
 */
function uwho_site_menu(){
  return array(
    'admin/settings/uwho-site' => array(
      'title' => 'UWho - Site settings',
      'description' => 'Alter the settings that allow other sites to automatically log users into this site',
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'uwho_site_settings'
      ),
      'access arguments' => array(
        'administer site configuration'
      ),
      'file' => 'uwho_site.settings.inc'
    ),
    'uwho' => array(
      'type' => MENU_CALLBACK,
      'title' => 'UWho callback',
      'page callback' => 'uwho_site_callback',
      'page arguments' => array(
        1
      ),
      'access arguments' => array(
        'access content'
      ),
      'file' => 'uwho_site.callback.inc'
    )
  );
}

/**
 * hook_user
 * 
 * - We need to delete the entry from uwho if a user is deleted
 */
function uwho_site_user($op, &$edit, &$account, $category = NULL){
  if($op == 'delete'){
    db_query('DELETE FROM {uwho} WHERE uid = %d', $account->uid);
  }
}