<?php

/**
 * Simply updates a node with the terms of nodes it is associated with.
 */

/**
 * Implementation of hook_nodeapi()
 */
/*
function also_term_nodeapi(&$node, $op){
  switch($op){
    case 'insert':
    case 'update':
      // The node is being inserted or updated, lets update this node, or other nodes.
      // 1. Does this node point at other nodes?
      $result = db_query("SELECT * FROM content_type_".$node->type." WHERE nid=".$node->nid);
      $node_associations = db_fetch_array($result);
      $node_associations_cols = array_keys($node_associations);
      $tids = array();
      foreach($node_associations_cols as $col){
        if($col != 'vid' && $col !='nid'){
          if(substr($col,-4)=='_nid'){
            // This is a node nid, get the terms from this node.
            if ($node_associations[$col]!=0){
              $result = db_query("SELECT tid FROM term_node WHERE nid = ".$node_associations[$col]);
              while($row = db_fetch_array($result)){
                $tids[] = $row['tid'];
              }              
            }
          }
        }
      }
      print_r($node);exit;
      taxonomy_node_save($node->nid,$tids);
      exit;
      // 2. Do other nodes point at this node?
  }
}
*/
/**
 * Cron, just for tidyness
 */
/*
function also_term_cron(){
  
  
}
*/