<?php

// We remove the pointless "Taxa" classification created by the classification
// module on install.  We only do this if there are no terms associated with it.

function classification_scratchpads_install(){
  if(!array_pop(db_fetch_array(db_query("SELECT COUNT(*) FROM {term_data} WHERE vid = (SELECT vid FROM {vocabulary} WHERE name = 'Taxa')")))){
    db_query("DELETE FROM {vocabulary} WHERE name = 'Taxa'");
  }  
}