#!/bin/bash

# Update the Sandbox
# Simply comment out the following lines (like this one) to
# stop the sandbox wipe process.

# Move the sandbox.html file into place
mv /var/lib/drupal6/all/modules/sandbox/sandbox.html.hidden /var/lib/drupal6/all/modules/sandbox/sandbox.html

# Recreate the database.
echo "DROP DATABASE sandboxscratchpadseu; CREATE DATABASE sandboxscratchpadseu;" | mysql -uroot -pOecey9cheehiphohngeiwi8lahH1ohNi

screen -D -m "./install_sandbox_help"

# Hide sandbox.html
mv /var/lib/drupal6/all/modules/sandbox/sandbox.html /var/lib/drupal6/all/modules/sandbox/sandbox.html.hidden
