<?php

function sandbox_block($op = 'list', $delta = 0, $edit = array()){
  switch($op){
    case 'list':
      return array(
        array(
          'info' => t('Sandbox timer')
        )
      );
    case 'view':
      $time_passed = time() - variable_get('sandbox_site_created', time());
      $time_left = format_interval(21600 - $time_passed);
      $time_passed = format_interval($time_passed);
      return array(
        'subject' => '',
        'content' => "<p style=\"display:block;margin-top:0;\">The Sandbox was last updated $time_passed ago. You have approximately $time_left before the site is wiped.</p><p style=\"display:block;margin-top:0;\">".l('Login', 'user')." to the site using the username: \"test\" and the password: \"pass\"</p>"
      );
  }
}

/**
 * Implementation of hook_form_alter
 * 
 * Following alters the install form, skipping it alltogether so that the sites
 * are installed automatically, with no user input.
 */
function sandbox_form_alter(&$form, $form_state, $form_id){
  echo $form_id;
  switch($form_id){
    case 'install_configure_form':
      $form_state = array(
        'storage' => NULL,
        'submitted' => TRUE,
        'values' => array(
          'site_name' => 'Scratchpad Sandbox',
          'site_mail' => 'scratchpad@mailinator.com',
          'account' => array(
            'name' => 'test',
            'mail' => 'scratchpad@mailinator.com',
            'pass' => 'pass'
          ),
          'date_default_timezone' => '3600',
          'clean_url' => '1',
          'update_status_module' => array(
            1 => 0
          ),
          'op' => 'Save and continue',
          'submit' => 'Save and continue',
          'form_id' => 'install_configure_form'
        )
      );
      scratchpadify_install_configure_form_submit($form, $form_state);
      break;
    case 'user_profile_form':
      if($form['#uid'] == 2){
        drupal_set_message(t('You can not edit the "test" user'), 'error');
        if(isset($_GET['destination'])){
          drupal_goto($_GET['destination']);
        }else{
          drupal_goto(referer_uri());
        }
      }
      break;
    case 'user_login':
      $form['login_details'] = array(
        '#value' => '<h1><b>Username:</b> test<br/><b>Password:</b> pass</h1>',
        '#weight' => -100
      );
      break;
    case 'system_site_information_settings':
      $form['site_mission']['#disabled'] = TRUE;
      $form['site_mission']['#description'] = '<p class="error">'.t('Editing of the mission statement on this site has been disabled.').'</p>';
      $form['#submit'] = array_merge(array('sandbox_settings_submit'), $form['#submit']);
      break;
  }
}

/**
 * Submit function to prevent editing of the mission statement.
 */
function sandbox_settings_submit($form, &$form_state){
  $form_state['values']['site_mission'] = variable_get('site_mission', '');
}