<?php
/**
 * implementation of hook_ispecies
 */
function googlescholar_ispecies(){
  return array (
    'googlescholar' => array (
      'title' => t ( 'Google Scholar' ), 
      'description' => t ( 'Some info about Google Scholar' ), 
      'callback' => 'googlescholar_ajax_callback' ) );
}

function googlescholar_init(){
  drupal_add_css ( drupal_get_path ( 'module', 'googlescholar' ) . '/googlescholar.css' );
}

function googlescholar_ajax_callback($term_name, $limit = 20, $offset = 0){
  $items = array ();
  $request = 'http://fencedine.myspecies.info/?url=' . urlencode ( 'http://darwin.zoology.gla.ac.uk/cgi-bin/gsaJSON.cgi?q=' . $term_name );
  $json_str = file_get_contents ( $request );
  $json_str = substr ( $json_str, strpos ( $json_str, 'gs_results' ) );
  $json_obj = json_decode ( $json_str );  
  //the json string returned includes a functon call which we do not want
  $json_str = str_replace ( 'gs_results({', '{', $json_str );
  $json_str = str_replace ( '})', '}', $json_str );  
  $json_obj = json_decode ( strval ( $json_str ) );  
  $counter = 0;
  $urls = array();
  if (is_array ( $json_obj->Result )) {    
    foreach ( $json_obj->Result as $key => $result ) {      
      $counter ++;      
      $item = array(
        'body' => sprintf ( '<a target="_blank" href="%s" title="%s">%s</a>', $result->link, $result->title, $result->title ),
        'page_url' => $result->link
      );
      $urls[] = $item['page_url'];
      $items[] = $item;
      if ($counter >= $limit) {
        break;
      }    
    }  
  }
  $urls = array('name'=> 'Google Scholar', 'url' => 'http://scholar.google.co.uk/scholar?q=' . $term_name, 'urls' => $urls);
  $items['urls'] = $urls;
  $items['citation'] = theme('citation_url', $urls);
  return $items;
}