<?php

/**
 * @file 
 * 
 * This is the Mado module file.  It does very little but load the include for
 * the alternative taxonomy/term/[x] pages.
 */

/**
 * Implementation of hook_menu
 */
function mado_menu(){  
  $items = array();  
  $items['taxonomy/term/%'] = array(
    'title' => 'Taxonomy term',
    'page callback' => 'mado_term_page',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'mado.pages.inc',
  );  
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function mado_theme() {
  return array(
    'mado_block' => array(
      'arguments' => array('block' => array()),
    ),
    'mado_row' => array(
      'arguments' => array('theme_row' => array()),
    )
  );
}

/**
 * Get the theme that this vocabulary is set to use.  Returns false if this 
 * vocabulary should use the standard layout.
 */
function mado_get_theme($vid){
  
  // THIS FUNCTION IS TEMPORARY, IT NEEDS FULLY WRITING WITH A WORKFLOW TO
  // ENABLE A USER TO ALTER A THEME.
  drupal_add_css(drupal_get_path('module','mado').'/mado.css');
  return array(
    'top' => array(
      // '#css' => 'mado_red',
      // '#title' => '' // CURRENTLY UNUSED
      'left' => array(
        //'#title' => t('Top left'),
        '#type' => 'view',
        '#name' => 'comments_recent',
        '#css' => 'mado_block_2',
        '#scroll' => 1
      ),      
      'right' => array(
        //'#title' => t('Top right'),
        '#type' => 'view',
        '#name' => 'taxonomy_images',
        '#css' => 'mado_block_2 mado_images',
        '#scroll' => 1
      ),    
    ),
    'middle' => array(
      //'#title' => '',
      //'#css' => '',
      'middle' => array(
        //'#title' => t('Bottom'),
        '#type' => 'view',
        '#name' => 'taxonomy_pages',
        '#css' => 'mado_block_1'    
      )
    ),
    'bottom' => array(
      'middle' => array(
        //'#title' => ''
        '#type' => 'block',
        '#name' => 'boost.status',
        '#css' => 'mado_block_1'
      )
    )
  );
}